### ISSUE TITLE
Option 'opt-bisect-limit' registered more than once!

### ISSUE THREAD

**Issue by xR3b0rn** [secure-software-engineering/phasar#130]
- [x] I have searched open and closed issues for duplicates
  - [x] I made sure that I am not using an old project version (DO: pull Phasar, update git submodules, rebuild the project and check if the bug is still there)

----------------------------------------

### Bug description
Not matter with what agruments I try to run phasar-llvm, I end up in this error:
```
$ phasar-llvm --help
: CommandLine Error: Option 'opt-bisect-limit' registered more than once!
LLVM ERROR: inconsistency in registered CommandLine options
```

### Steps to reproduce
1.
  - build newest llvm from source
  - build phasar from source
2.
```
# LLVM
apt-get install libllvm-10-ocaml-dev libllvm10 llvm-10 llvm-10-dev llvm-10-doc llvm-10-examples llvm-10-runtime
# Clang and co
apt-get install clang-10 clang-tools-10 clang-10-doc libclang-common-10-dev libclang-10-dev libclang1-10 clang-format-10 python-clang-10 clangd-10
# libfuzzer
apt-get install libfuzzer-10-dev
# lldb
apt-get install lldb-10
# lld (linker)
apt-get install lld-10
# libc++
apt-get install libc++-10-dev libc++abi-10-dev
# OpenMP
apt-get install libomp-10-dev
```
```
git clone https://github.com/secure-software-engineering/phasar.git
mkdir phasar/build
cd phasar/build
cmake -DCMAKE_BUILD_TYPE=Release ..
sudo make -j install
ldconfig
```
```
phasar-llvm --help
```
### Context (Environment)

**Operating System:**
  - [x] Linux (Ubuntu 18.04.4 LTS WSL)
  - [ ] Windows
  - [ ] macOS

**Build Type:** 
  - [x] cmake
  - [ ] custom build

**Comment by pdschubert** [comment]
Hi,

This is most likely because you linked statically against the LLVM/Clang libraries. Please try to link dynamically against LLVM/Clang. If you already linked against their dynamic versions please let me know.

**Comment by xR3b0rn** [comment]
I did not change the CMakeLists.txt nor anything else in the phasar project. So I don't understand where I linked the wrong library?

**Comment by bsauce** [comment]
I have the same problem too. I use `./bootstrap.sh` to install phasar. That's strange.

**Comment by bsauce** [comment]
> I have the same problem too. I use `./bootstrap.sh` to install phasar. That's strange. And my environment is Ubuntu 18.04.

I think it is because `./bootstrap.sh` install the newest clang-10.0.0. But some code in phasar use the old version of clang/llvm.
