### ISSUE TITLE
build phasar with llvm 9.0.0

### ISSUE THREAD

**Issue by xR3b0rn** [secure-software-engineering/phasar#136]
Compiling phasar from master with llvm 9.0.0 installed gives this error:
```
include/phasar/PhasarLLVM/DataFlowSolver/IfdsIde/LLVMZeroValue.h:27:10: fatal error: 'llvm/Support/Alignment.h' file not found
```
There is no Alignment.h in this folder:
https://github.com/llvm/llvm-project/tree/llvmorg-9.0.1/llvm/include/llvm/Support

Isn't it possible to build phasar with llvm 9.0.0 as described in the readme?

**Comment by MMory** [comment]
Hi @xR3b0rn that's a file that belongs to llvm 10. llvm 9 is not supported anymore and unfortunately the readme is not updated yet.
