### ISSUE TITLE
Analysis of small exsample program

### ISSUE THREAD

**Issue by xR3b0rn** [secure-software-engineering/phasar#138]
- [x] I have searched open and closed issues for duplicates
  - [x] I made sure that I am not using an old project version (DO: pull Phasar, update git submodules, rebuild the project and check if the bug is still there)

----------------------------------------

### Bug description
main.cpp:
```
void function(int& a)
{
    a = 5;
}
int main()
{
    int a = 0;
    function(a);
}
```
Command line:
```
$ /usr/local/llvm-10/bin/clang++ -emit-llvm -S main.cpp
$ /usr/local/phasar/bin/phasar-llvm -m main.ll -D ifds-solvertest
PhASAR v0320
A LLVM-based static analysis framework

No text report available!
```
I get "No text report available!" for almost all DataFlowAnalysisType listed [here](https://github.com/secure-software-engineering/phasar/wiki/Getting-Started:-Running-an-Analysis).
### Steps to reproduce
  - pull from master
  - execute bootstrap.sh
  - do the steps described in "Bug description"

### OS
  - [x] Linux
  - [ ] Windows
  - [ ] macOS

**Comment by pdschubert** [comment]
The "ifds-solvertest" analysis is an exemplary analysis that does not compute any interesting result -- it is only used as a solver test.

However, you can still force Phasar (phasar-llvm) to show you the computed data-flow results by specifying the command-line flag **--emit-raw-results**.

If you have any more questions, I can also add you to our Phasar Slack channel -- just drop me an email in case you wish to be added.

Cheers

**Comment by xR3b0rn** [comment]
I mailed you. (philipp.schubert@upb.de)
