### ISSUE TITLE
How to build on Mac

### ISSUE THREAD

**Issue by ChaosLee03** [secure-software-engineering/phasar#144]
Hello
        I have followed the Turoial to build phasar, but have some problem in brew bundle. Some dependencies such as: libsqlite3-dev and zlib1g-dev can't brew.

**Comment by pdschubert** [comment]
Hi there.

One of our student assistants recently fixed the macOS support. Could you please try if you can compile the project using the following steps:

Step 1: Installation
`$ brew install boost`
`$ brew install python3`
// Install llvm version 10
`$ brew install llvm`

STEP 2: Setting path
// To be set to llvm clang not to apple clang
`export CC=/usr/local/opt/llvm/bin/clang`
`export CXX=/usr/local/opt/llvm/bin/clang++`
Set PATH env variable to - /usr/local/opt/llvm/bin

STEP 3: Compilation
Go to Phasar directory run the following commands
`$ git submodule init`
`$ git submodule update`
`$ mkdir build`
`$ cd build/`
`$ cmake -DCMAKE_BUILD_TYPE=Release ..`
`$ make -j $(nproc)` # or use a different number of cores to compile it
`$ sudo make install` # if you wish to install Phasar system wide

Step 4: Testing
// To get the manual and help message
`$ phasar-llvm --help`
// To run sample analysis make sure to generate the .ll file before running the analysis
`$ phasar --module test/build_systems_tests/installation_tests/module.ll -D IFDS_SolverTest`
// To generate .ll file
`clang++ -emit-llvm -S fileName.cpp`

Cheers,
Philipp

**Comment by ChaosLee03** [comment]
Thx, I will try!
