### ISSUE TITLE
cmake doesn't have -j option.

### ISSUE THREAD

**Issue by dbwodlf3** [secure-software-engineering/phasar#184]
https://github.com/secure-software-engineering/phasar/blob/82733aeb1509e6e349285757f8d889fb1fab3d9d/bootstrap.sh#L134

cmake jobs option is only available over Cmake 3.12
under that versions are unavailable.

:(

https://stackoverflow.com/questions/36633074/set-the-number-of-threads-in-a-cmake-build
https://cmake.org/cmake/help/v3.0/manual/cmake.1.html

**Comment by dbwodlf3** [comment]
https://github.com/secure-software-engineering/phasar/pull/185
I sent PR!

**Comment by pdschubert** [comment]
Since we are using `ninja` as a build system we won't need the `-j` option any longer. `ninja` determines a suitable number of processors by itself. It should be fixed on github:development.

Thanks for reporting that issue.

Best,
Philipp
