### ISSUE TITLE
Assertion violation at llvm/IR/GlobalVariable.h:137

### ISSUE THREAD

**Issue by rainoftime** [secure-software-engineering/phasar#192]
### Bug description

When I try to analyze a bitcode built from SPEC 2017,
phasar throws an assertion failure

[field_discretization.o.bc.zip](https://github.com/secure-software-engineering/phasar/files/5188134/field_discretization.o.bc.zip)

~~~~
phasar-llvm: /home/testusr/local/include/llvm/IR/GlobalVariable.h:137: const llvm::Constant *llvm::GlobalVariable::getInitializer() const: Assertion `hasInitializer() && "GV doesn't have initializer!"' failed
~~~~

### Steps to reproduce

~~~~
unzip file.bc.zip
/phasar/build/tools/phasar-llvm/phasar-llvm -m file.bc
~~~~

### Context (Environment)

Phasar commit ID: 82733aeb150
OS: CentOS 7
LLLVM version: 10.0.1

**Comment by pdschubert** [comment]
Thanks for reporting a bug. We found the bug and will commit a fix as soon as possible.

The assertion was triggered because the `typeinfo for dealii::Subscriptor` -> `_ZTIN6dealii11SubscriptorE` is not defined (but only declared) in the LLVM IR file; we will fix that.

**Comment by pdschubert** [comment]
The bug is now fixed on the `development` branch.

Thanks again for reporting the issue.
