### ISSUE TITLE
LLVM ERROR: Could not retrieve function for entry point

### ISSUE THREAD

**Issue by legendtang** [secure-software-engineering/phasar#197]
- [x] I have searched open and closed issues for duplicates
  - [x] I made sure that I am not using an old project version (DO: pull Phasar, update git submodules, rebuild the project and check if the bug is still there)

----------------------------------------

### Bug description
When I try to analyze a bitcode built from SPEC 2017,
phasar throws a fatal failure

[wrf_r_base.mytest-m64.bc.zip](https://github.com/secure-software-engineering/phasar/files/5239336/wrf_r_base.mytest-m64.bc.zip)

LLVM ERROR: Could not retrieve function for entry point

**Expected result:** It should analyze and exit normally.

### Steps to reproduce
run the above bitcode with any modes.

### Context (Environment)

Phasar commit ID: 82733ae
OS: CentOS 7
LLLVM version: 10.0.1

**Build Type:** 
  - [x] cmake
  - [ ] custom build

### Possible solution

Add some checks to it.

**Comment by pdschubert** [comment]
Thanks for reporting. However, this particular behavior is not an issue. As default, if no custom entry points are specified, Phasar will fallback and try to use `main()` as an entry points. Because the given test program does not contain a `main()` function Phasar complains that it cannot retrieve the function.

I'll update the error message such that Phasar gives some more details on what's wrong.

Cheers,
Philipp

**Comment by legendtang** [comment]
> Thanks for reporting. However, this particular behavior is not an issue. As default, if no custom entry points are specified, Phasar will fallback and try to use `main()` as an entry points. Because the given test program does not contain a `main()` function Phasar complains that it cannot retrieve the function.
> 
> I'll update the error message such that Phasar gives some more details on what's wrong.
> 
> Cheers,
> Philipp

@pdschubert 

By any modes, I mean I am running phasar for different pointer analyses and print their results, which definitely has entry points. E.g., `pharsar-llvm --pointer-analysis=CFLAnders --call-graph-analysis=CHA`. What I mean is that other bitcodes look fine with this setting, so this is definitely a bug.

**Comment by legendtang** [comment]
> Thanks for reporting. However, this particular behavior is not an issue. As default, if no custom entry points are specified, Phasar will fallback and try to use `main()` as an entry points. Because the given test program does not contain a `main()` function Phasar complains that it cannot retrieve the function.
> 
> I'll update the error message such that Phasar gives some more details on what's wrong.
> 
> Cheers,
> Philipp
Ok, I understand your point. But I am running pointer analyses only without using data-flow analyses. Why this has to specify an entry point?
