### ISSUE TITLE
Missing callgraph functions with FFTW library

### ISSUE THREAD

**Issue by btruong-pjr** [secure-software-engineering/phasar#206]
- [X] I have searched open and closed issues for duplicates
  - [X] I made sure that I am not using an old project version (DO: pull Phasar, update git submodules, rebuild the project and check if the bug is still there)

----------------------------------------

### Bug description
There are missing functions from the callgraph when using libfftw.

### Steps to reproduce
  - Compile libfftw-3.3.7
  - Compile sample fftw program
  - Generate callgraph
  - Verify callgraph does not contain missing functions
**Actual result:** I ran a dynamic analysis to generate a callgraph of what functions were actually being called. The results are in 
[dynamic_functions.txt](https://github.com/secure-software-engineering/phasar/files/5394685/dynamic_functions.txt)

**Expected result:** Attached is the callgraph that shows these functions as missing:
[callgraph.log](https://github.com/secure-software-engineering/phasar/files/5394687/callgraph.log)
apply_cpy2dco
apply_ip_sq
apply_ip_sq_tiled
apply_ip_sq_tiledbuf
apply_iter
apply_tiled
apply_tiledbuf
compare_by_istride
copy
dotile
dotile
dotile_buf
dotile_buf
fftwf_cpy1d
fftwf_cpy2d_tiled
fftwf_cpy2d_tiledbuf
fftwf_dft_solve
fftwf_null_awake
fftwf_rdft_solve
fftwf_tile2d
fftwf_transpose
fftwf_transpose_tiled
fftwf_transpose_tiledbuf
okp
okp
transpose
transpose_rec

### Context (Environment)

  - **phasar:** \[cd94f1a48d05161c44e166074e94be90f95d2c6c]
  - **googletest:** \[042e412c36880afc882bebfe3f79024bf7aa24b7]
  - **json:** \[042e412c36880afc882bebfe3f79024bf7aa24b7]
  - **WALi-OpenNWA:** \[73f9d7a03367b2c485cec35c4bea0d02e7e87742]

**Operating System:**
  - [X] Linux
  - [ ] Windows
  - [ ] macOS

**Build Type:** 
  - [X] cmake
  - [ ] custom build

### Possible solution

We are happy to discuss possible solutions to this problem, especially if it origniates from a design flaw.

### Example files

**Files:**
[fftw_sample.tar.gz](https://github.com/secure-software-engineering/phasar/files/5411932/fftw_sample.tar.gz)
[callgraph.tar.gz](https://github.com/secure-software-engineering/phasar/files/5411832/callgraph.tar.gz)

**Comment by MMory** [comment]
We're working on this. Phasar isn't handling c-style polymorphism correctly. Thank you very much for reporting this issue.

**Comment by MMory** [comment]
#212 should fix the issue. @pdschubert is going to review the fix before we merge it as it is quite extensive.

The callgraph generated for the fftw sample now contains the calls to the functions listed above. Only `compare_by_istride` is missing, but that is expected as this one is passed into the c standard lib as function pointer and called from there, but the c standard lib is not present in the ll file and hence not analysed.

**Comment by MMory** [comment]
#212 was just merged to development. Hence I close this issue.
