### ISSUE TITLE
error while loading shared libraries: libphasar_controller.so: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by amordahl** [secure-software-engineering/phasar#208]
- [x] I have searched open and closed issues for duplicates
  - [x] I made sure that I am not using an old project version (DO: pull Phasar, update git submodules, rebuild the project and check if the bug is still there)

----------------------------------------

### Bug description
phasar-llvm fails with the following bug message: "/usr/local/phasar/bin/phasar-llvm: error while loading shared libraries: libphasar_controller.so: cannot open shared object file: No such file or directory"

### Steps to reproduce
  - Set up an Ubuntu 18.04 virtual machine through vagrant.
  - Install gcc, g++, cmake 3.18 and boost 1.74.0
  - Run the install script with -DBOOST_DIR to ~/boost_1_74_0 (where boost was downloaded and installed). 
  - Ran sudo ./bootstrap.sh from the ~/phasar directory.
  - Script finished successfully, and indicated that phasar was installed at /usr/local.
  - Ran /usr/local/phasar/bin/phasar-llvm --module test/build_systems_tests/installation_tests/module.ll -D ifds-solvertest.

**Actual result:** Got an error message as indicated in the description above.
 
**Expected result:** Phasar running the analysis.

### Context (Environment)

  - **phasar:** \[8dec0c4664e90f97a731e4874e2da4d483e2ba5b]
  - **googletest:** \[2fe3bd994b3189899d93f1d5a881e725e046fdc2]
  - **json:** \[e3c28afb61227043dd7c0f9168b9394dfb016f87]
  - **WALi-OpenNWA:** \[2bb4aca02c5a5d444fd038e8aa3eecd7d1ccbb99]

**Operating System:**
  - [x] Linux
  - [ ] Windows
  - [ ] macOS

**Build Type:** 
  - [x] cmake
  - [ ] custom build

### Possible solution

We are happy to discuss possible solutions to this problem, especially if it origniates from a design flaw.

### Example files

**Files:**

**Comment by pdschubert** [comment]
Hi Austin,

could you please check if the Phasar's libraries are correctly installed at `/usr/local/lib/`? This directory is usually home to all of the `libphasar_*` libraries.

If the libraries are installed correctly, you may forgot to tell the dynamic linker about it. It's probably best to export the following variables and to add those lines to the end of your `~/.bashrc`:
```
# Path
export PATH=${PATH}:/usr/local/phasar/bin
# Lib
export LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:/usr/local/phasar/lib
export LIBRARY_PATH=${LIBRARY_PATH}:/usr/local/phasar/include
# Phasar
export PHASAR_INCLUDE_DIR=/usr/local/phasar/include
export PHASAR_LIBRARY_DIR=/usr/local/phasar/lib
```
After having exported the variables run:
```
sudo ldconfig
```
to update the run-time linker.

Cheers,
Philipp

**Comment by amordahl** [comment]
Thanks Philipp. My libraries were installed at `/usr/local/phasar/lib`. Adding the variables to the end of my shell config file solved my issue. Thanks!
