### ISSUE TITLE
Broken build on LLVM 11

### ISSUE THREAD

**Issue by legendtang** [secure-software-engineering/phasar#209]
**Is your feature request related to a problem? Please describe.**
Since the homebrew version of LLVM has been upgraded to LLVM 11, the build is broken due to some major API changes. E.g., the LLVM call site header is moved.

**Describe the solution you'd like**
Fix the build

**Comment by MMory** [comment]
I had a brief look into this. As you said, there are some major API changes and we cannot support LLVM<11 and LLVM>=11 at the same time. We need to discuss internally when we make the switch to LLVM 11, it is not going to happen immediately.

**Comment by legendtang** [comment]
Maybe `LLVM_VERSION_MAJOR` is still a way to support all versions, if the API changes are not substantial.

**Comment by blipper** [comment]
There are two questions
1) Is there a need for Phasar to support both versions >=1 1 and <11?  
2) If 1 is true  then how to do so?  Based on my conversion efforts I actually think it is feasible with some macro magic but if we don't need to support both at same time can we just merge in the 11 branch then and document that users need 11 plus?

**Comment by MMory** [comment]
Hi Martin, no, on our side there is no need to support both >=11 and <11. We have a feature branch for the transition to 11+ which should soon be merged to development and master, there are just some failing test cases. We would like to avoid the macro magic that would be needed to support both >=11 and <11.

**Comment by pdschubert** [comment]
Hi all, I finally have some time to work on Phasar's code base again.
I set `development` as the new default branch. The `development` branch supports LLVM 12 now (and reflects all changes in terms of `llvm::ImmutableCallSite` --> `llvm::CallBase`). The `master` branch still uses LLVM 10, however, will be updated relatively soon.

I would like to close this issue if no one complains?

**Comment by blipper** [comment]
LTGM!  Thanks!
