### ISSUE TITLE
Generating json output

### ISSUE THREAD

**Issue by caballa** [secure-software-engineering/phasar#21]
I would like to see the output of the call graph analysis (`-C CHA`) and also of the class hierarchy analysis ('-H yes'). I'm using this command:

```
phasar -m test.ll -P CFLAnders -H yes -C CHA -S yes -O myresults.json 
```

However, the content of `myresults.json` is always `null`.
What am I missing?

**Comment by caballa** [comment]
The file `myresults.json` is populated if I run a dataflow analysis `-D ....`. 
Is there any way to visualize the results of the CHA?

**Comment by caballa** [comment]
I tried with the docker version and it works so it seems there is something wrong with my installation from sources.

**Comment by BushraAloraini** [comment]
This seems to be still an issue! I have tried Phasar on mac-os and the VirtualBox provided! both generated a result.json file that includes "null".

**Comment by ChaosLee03** [comment]
> I tried with the docker version and it works so it seems there is something wrong with my installation from sources.

Have you solved the problem?
