### ISSUE TITLE
No text report for IFDS analyses

### ISSUE THREAD

**Issue by SViktorS** [secure-software-engineering/phasar#210]
- [x] I have searched open and closed issues for duplicates
  - [x] I made sure that I am not using an old project version (DO: pull Phasar, update git submodules, rebuild the project and check if the bug is still there)

----------------------------------------

### Bug description
I don't get a report when using the ifds command line analyses. I get only a report for IDE-LCA. For the other analyses I get "No text report available!" But I think I should get one.

### Steps to reproduce
I used the following short c++ code and its corresponding LLVM-IR.
 ```
int main() {
        int i = 14;
        int s;
        int j = 20;
        i = 51;
        int k = i + j;
        return 0;
}
```
```
define dso_local i32 @main() #0 {
  %1 = alloca i32, align 4
  %2 = alloca i32, align 4
  %3 = alloca i32, align 4
  %4 = alloca i32, align 4
  %5 = alloca i32, align 4
  store i32 0, i32* %1, align 4
  store i32 14, i32* %2, align 4
  store i32 20, i32* %4, align 4
  store i32 51, i32* %2, align 4
  %6 = load i32, i32* %2, align 4
  %7 = load i32, i32* %4, align 4
  %8 = add nsw i32 %6, %7
  store i32 %8, i32* %5, align 4
  ret i32 0
}
```
I tried the following commands:
`phasar-llvm -m constant.ll -D ifds-uninit`
and
`phasar-llvm -m constant.ll -D ifds-const`

**Actual result:** 
```
PhASAR v0320
A LLVM-based static analysis framework

No text report available!
```

**Expected result:** 
I expected a report like the one that is printed by the IDE-LCA.
```
====================== IDE-Linear-Constant-Analysis Report ======================

WARNING: No Debug Info available - emiting results without source code mapping!

Function: main
--------------
At IR statement: store i32 14, i32* %2 | ID: 6
   Fact: %1 = alloca i32 | ID: 0
  Value: 0

At IR statement: store i32 20, i32* %4 | ID: 7
   Fact: %2 = alloca i32 | ID: 1
  Value: 14
   Fact: %1 = alloca i32 | ID: 0
  Value: 0
...
...
...
```

I took a look inside your code and both analyses have implemented the "emitTextReport" function from the IFDSTabulationProblem.h file but somehow only the virtual base function is called in IFDS analyses.  

### Context (Environment)

  - **phasar:** \[8dec0c4664e90f97a731e4874e2da4d483e2ba5b]

**Operating System:**
  - [x] Linux
  - [ ] Windows
  - [ ] macOS

**Build Type:** 
  - [x] cmake
  - [ ] custom build

**Comment by pdschubert** [comment]
Hi Viktor,

Unfortunately, we do not have the resources to provide rigor implementations for `emitTextReport()` for all of the analysis. Please use the command-line flag `--emit-raw-results` to dump the complete solver results. However, we welcome any contributions to this end.

Cheers,
Philipp
