### ISSUE TITLE
Writing IFDS/IDE analysis

### ISSUE THREAD

**Issue by zhaogang92** [secure-software-engineering/phasar#22]
Hi,

I am new to use this great framework, so not quite familiar with it. Currently in my problem, I defined more than one entry points, in those flow functions, is it possible to quickly know each instruction is reached by which entry point?

**Comment by zhaogang92** [comment]
Thanks for your quick reply! I didn't try defining my own fact type before since I still need to do analysis on instructions. But definitely I can create a type include both information. It seems a good solution. I'll try it first.

**Comment by zhaogang92** [comment]
Hi, @MarcelHB , I have a followup question. So I defined two entry points for two functions, say func1 and func2. I assigned ID 1 to func1 and ID 2 to func2. But func2 is actually called in func1, as below:

```C
func1() {
  func2();
  ...
}
```

I used Identity flow function for normal flow, CalltoReturn and CallFlow, KillAll for RetFlow. In the result, all statements in func2 got ID 1 (except the first statement since we assigned that in the initialSeeds function). From the log information, I can see that func2 is processed first. I guess the result of statements in func2 is later overwritten when processing func1? I also tried using KillAll for CallFlow, but in this case no result of func2 is reported.

I expect that all statements in func1 have ID 1, and statements in func2 have ID 2 (or 1 and 2). What changes should I make to get this?

Thanks!

**Comment by MarcelHB** [comment]
I cannot do any tests right now, so this is a bit of free-hand code. I assume you have a fact type that somewhat looks like this:
```cpp
struct Fact {
  const std::string name;
  Fact (const std::string& S) : name{S} {}
};
```
Your problem, let's call it `ReachabilityProblem`, is then derived from:
```cpp
class ReachabilityProblem : public psr::DefaultIFDSTabulationProblem<const llvm::Instruction*, Fact*, const llvm::Function*, psr::LLVMBasedICFG&>;
```
There's a method:
```cpp
void ReachabilityProblem::printDataFlowFact (std::ostream &os, Fact *f) const override {
  os << f->name;
}
```
and also something that looks like:
```cpp
std::map<const llvm::Instruction *, std::set<Fact*>> ReachabilityProblem::initialSeeds () {
  std::map<const llvm::Instruction *, std::set<Fact*>> seedMap;

  for (auto &entryPoint : entryPoints) {
    someFactList.emplace_back(std::make_unique<Fact>(entryPoint));
    Fact *f = someFactList.back().get();

    seedMap.insert(
      std::make_pair(
          &icfg.getMethod(entryPoint)->front().front()
        , std::set<D_Type*>({f})
      )
    );
  }

  return seedMap;
}
```

Now, in every flow method (except `getSummaryFlowFunction`, there it is `nullptr`), there's just:
```cpp
return psr::Identity<Fact*>::getInstance();
```

Does this resemble your setup that causes this confusing output?

**Comment by zhaogang92** [comment]
Yes almost the same, though I also tried KillAll in some flow methods. When there is no overlap between the two entry point function, it works well. But for the example code I mentioned above, it's confusing. I am not sure if it's because I have a wrong understanding about the IFDS algorithm.

**Comment by MarcelHB** [comment]
Ok, I'm out of precise ideas, sorry. I recommend to check if you maintain some kind of state outside of a fact instance that is then inappropriately modified, or to trace calls to flow functions over the given fact manually.

**Comment by zhaogang92** [comment]
OK. Thanks!
