### ISSUE TITLE
No such file or directory  #include <phasar/PhasarLLVM/IfdsIde/LLVMDefaultIFDSTabulationProblem.h>

### ISSUE THREAD

**Issue by little-77** [secure-software-engineering/phasar#220]
- [x] I have searched open and closed issues for duplicates
  - [x] I made sure that I am not using an old project version (DO: pull Phasar, update git submodules, rebuild the project and check if the bug is still there)

----------------------------------------

### Bug description
Describe here the issue that you are experiencing.
when I compile the "06_static_analysis_part2_material", it tells me that this file can't be found. I use the "Latest (v0320) VirtualBox image – DECA.ova"

### Steps to reproduce
  - using hyphens as bullet points
  - list the steps
  - that reproduce the bug
  - e.g. cli arguments and flags

```
unzip 06_static_analysis_part2_material
cd 06_static_analysis_part2_material
mkdir build
cmake ..
make
```

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)

[![Bzhls1.png](https://s3.ax1x.com/2020/11/12/Bzhls1.png)](https://imgchr.com/i/Bzhls1)

**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)

### Context (Environment)

  - **phasar:** \[commit-id]
  - **googletest:** \[commit-id]
  - **json:** \[commit-id]
  - **WALi-OpenNWA:** \[commit-id]

**Operating System:**
  - [x] Linux
  - [ ] Windows
  - [ ] macOS

**Build Type:** 
  - [x] cmake
  - [ ] custom build

### Possible solution

We are happy to discuss possible solutions to this problem, especially if it origniates from a design flaw.

### Example files

**Files:**

**Comment by pdschubert** [comment]
Hi,

Thanks for your interest in Phasar. The materials that you are trying to compile are rather outdated. Phasar has undergone various changes which is why the file in question cannot be found in the latest version of the framework.

Is there anything you wish to accomplish in particular? If so, please drop us an email or send us a message in the Phasar Slack channel. We are happy to help.

Best,
Philipp
