### ISSUE TITLE
SVF & Phasar

### ISSUE THREAD

**Issue by xfang96** [secure-software-engineering/phasar#221]
Hello,
I am new to static analysis.
What is the difference between phasar and SVF? SVF is also a data-flow analysis framework based on SSA. Which framework should I choose? 
Looking forward to your reply. Thanks.

**Comment by pdschubert** [comment]
Hi.

Thanks for your interest in Phasar. Please drop us an email or ask these kind of questions in the Phasar Slack channel.

That is a tough question to answer in just a few sentences. As far as I know, SVF is especially well suited for computing inter-procedural points-to as well as value-flow (similar to def-use chains) information. Phasar is a more general static analysis framework that allows you to compute general data-flow information for arbitrary analysis problem.

If you have more concrete questions, please send us an email or write us on Slack.

Best,
Philipp
