### ISSUE TITLE
Improvements and minor changes in the shell scripts

### ISSUE THREAD

**Issue by vaibhav-hexa** [secure-software-engineering/phasar#228]
Hello,
To add few improvements and minor changes in the shell `scripts`. Please see the below list for the overview of the changes:

- Boost version check for installations with versions like 1._xy_.**0**
- Typo with `DO_UNIT_TESTS` corrected to `DO_UNIT_TEST`
- Added `|| exit ` for `cd` incase if it fails, so the script will exit
- Double-quoted the variables: `${var}` to `"${var}"`
- Command substitution with `$(...)` instead of `` `...` ``

Related PR: https://github.com/secure-software-engineering/phasar/pull/227

**Comment by MMory** [comment]
Closing as PR was merged.
