### ISSUE TITLE
Need a generic translation_functions_set

### ISSUE THREAD

**Issue by qtcdxxyuc** [secure-software-engineering/phasar#230]
**Is your feature request related to a problem? Please describe.**
We often write translate functions for different instructions.When a lot of instructions need to be processed, I think `if-else` mode not good.

`e.g.` `if (const auto *Ret = llvm::dyn_cast<llvm::ReturnInst>(ExitStmt)){...}`

**Describe the solution you'd like**

```c++
using const llvm::instruction* N_t;
TranslationFunctions<Ret(N_t,N_t)> trans;
trans.registered<llvm::ReturnInst>([](N_t curr,N_t succ){
    inst = llvm::dyn_cast<llvm::ReturnInst>(curr);
    // do some thing
});
// ...
trans.handle(curr,succ);
```

**Describe alternatives you've considered**
I have a simple implementation.

```c++
template <typename TRANSFUNC>
class TranslateFuncations;

template <typename Ret, typename... Args>
class TranslateFuncations<Ret(Args...)> {
public:
    static_assert(sizeof...(Args) >= 1);
    using FirstArg = typename std::tuple_element<0, std::tuple<Args...>>::type;
    static_assert(std::is_base_of_v<llvm::Instruction, typename std::remove_pointer_t<std::decay_t<FirstArg>>>);

    using Handler = std::function<std::optional<Ret>(Args...)>;
    static TranslateFuncations Create(std::function<void(TranslateFuncations&)>&& lambda) noexcept {
        TranslateFuncations value;
        lambda(value);
        return value;
    }

    template <typename CurrentInstruction>
    void registered(std::function<Ret(Args...)>&& lambda) noexcept {
        static_assert(std::is_base_of_v<llvm::Instruction, CurrentInstruction>);
        Handler handler = [inner = std::move(lambda)](Args... args) -> std::optional<Ret> {
            auto tuple = std::make_tuple(args...);
            if (not llvm::isa<CurrentInstruction>(std::get<0>(tuple))) return std::nullopt;
            return std::apply(inner, move(tuple));
        };
        handlers_.emplace_back(std::move(handler));
    }

    std::optional<Ret> handle(Args... args) {
        std::optional<Ret> result = std::nullopt;
        for (auto& handler : handlers_) {
            result = handler(args...);
            if (result) break;
        }
        return result;
    }

private:
    std::vector<Handler> handlers_;
};
```

I don’t know how to get the opcode of the instruction statically, so it uses vector traversal.

**Comment by MMory** [comment]
Hi, I don't understand the issue that you are referring to. What is wrong with `if (const auto *Ret = llvm::dyn_cast<llvm::ReturnInst>(ExitStmt)){...}`?

**Comment by qtcdxxyuc** [comment]
This is a suggestion.

Often need to deal with different instructions differently.like this:

```c++
if (const auto *Foo = llvm::dyn_cast<llvm::FooInst>(Stmt)){...}
if (const auto *Bar = llvm::dyn_cast<llvm::BarInst>(Stmt)){...}
if (const auto *Baz = llvm::dyn_cast<llvm::BazInst>(Stmt)){...}
```

I think this code is  beautiful.

```c++
using const llvm::instruction* N_t;
TranslationFunctions<Ret(N_t,N_t)> trans;
trans.registered<llvm::FooInst>([](N_t curr,N_t succ){
 	// ...
});
trans.registered<llvm::BarInst>([](N_t curr,N_t succ){
 	// ...
});
// ...
trans.handle(curr,succ);
```

Then I provide a simple template implementation.

**Comment by MMory** [comment]
With your approach the distinction of statements is apparently moved into the flow function itself. It seems like your instantiate a TranslationFunctions for every flow function then? I still don't get the value added, but to me it seems that unnecessary complexity is added. The current way allows to use one of the predefined flow functions such as Identity, GenIf etc. to be used, which makes the analysis code very straightforward to read and understand. Of course you are free to use TranslationFunctions etc. in your analyses, but I am not convinced that this should be part of mainline PhASAR.
