### ISSUE TITLE
Missing callgraph edges from pointer arithmetic in libmetal

### ISSUE THREAD

**Issue by ddiepo-pjr** [secure-software-engineering/phasar#236]
- [x] I have searched open and closed issues for duplicates
  - [x] I made sure that I am not using an old project version (DO: pull Phasar, update git submodules, rebuild the project and check if the bug is still there)

----------------------------------------

### Bug description
Missing edges in the callgraph using OTF from an application using libmetal, in particular the edge is computed from a function pointer which is derived from pointer arithmetic.

The source code in question can be found here:
https://github.com/Xilinx/libmetal/blob/master/lib/system/linux/device.c
I'm expecting to find a call graph edge to: `metal_uio_dev_open()` from `metal_linux_dev_open()`.  I do see edges into `metal_linux_dev_open()`, and a few other edges out from `metal_linux_dev_open()`.

I expect the invoke "ldrv->dev_open()" on line 552 to produce the edge into metal_uio_dev_open().  The macro called at line 535 `to_linux_bus` does pointer arithmetic to obtain the struct's pointer from the struct's member using these fancy macros:

https://github.com/Xilinx/libmetal/blob/master/lib/utilities.h:
```
/** Compute offset of a field within a structure. */
#define metal_offset_of(structure, member)		\
	((uintptr_t) &(((structure *) 0)->member))
/** Compute pointer to a structure given a pointer to one of its fields. */
#define metal_container_of(ptr, structure, member)	\
	(void *)((uintptr_t)(ptr) - metal_offset_of(structure, member))
```

### Steps to reproduce
  I have a proprietary third-party application which is using libmetal, the IR was created using wllvm.  Unfortunately I cannot provide this, and will work to identify if a small sample application using libmetal can be created instead.  However, I can easily reproduce this using the OTF resolver from this application to produce a callgraph.

**Actual result:** The call graph edge to: `metal_uio_dev_open()` from `metal_linux_dev_open()` is missing

**Expected result:** The call graph edge to: `metal_uio_dev_open()` from `metal_linux_dev_open()` is present in the graph.

### Context (Environment)

  - **phasar:** \[1c8dcfca227eb35414bf8c853a917c250edc36e6]
  - **googletest:** \[2fe3bd994b3189899d93f1d5a881e725e046fdc2]
  - **json:** \[e3c28afb61227043dd7c0f9168b9394dfb016f87]
  - **WALi-OpenNWA:** \[2bb4aca02c5a5d444fd038e8aa3eecd7d1ccbb99]

**Operating System:**
  - [X] Linux
  - [ ] Windows
  - [ ] macOS

**Build Type:** 
  - [X] cmake
  - [ ] custom build

### Possible solution

Nothing known at this time

### Example files

I'll work on finding a sample application, and/or collecting additional debug.
**Files:**

**Comment by MMory** [comment]
Could you try with the most recent state of the development branch, please? I recently fixed a bug that is at least related.

**Comment by ddiepo-pjr** [comment]
@MMory -- short version: I'll probably close this out.

The code being analyzed is intended to run on an arm, but I was compiling it and its libraries first for x86 to take an initial stab at it.  It was on x86 that I noticed this missing edge.  Since then we have been able to use clang to cross compile for arm and using that IR this edge is no longer missing.  I do still have some other missing edges I need to look into, which are in similar parts of the code so they may be related.  I also do not understand why there would be a difference between the platforms.  I'll look into those things and update here once I know more.

**Comment by ddiepo-pjr** [comment]
Closing this out.  If time allows I'll review the x86-compile created IR vs. IR from the arm cross-compile.  Clearly PhASAR is handling this properly (both master & the current development branch) since it works for the latter IR.  Other similar functions which at first glance appeared to be missing were a result of function in-lining.
