### ISSUE TITLE
LLVM ERROR: Could not retrieve function for entry point

### ISSUE THREAD

**Issue by bingosxs** [secure-software-engineering/phasar#244]
We encounter this error when analyzing an cpp file without main.
And We assign the entry point which is an function from A_cpp.ll .
A.cpp  contains a group functions for the main.cpp.
And idea to solve this?

The error is shown below:
```

root@4d7c82a668eb:src/build_DBG.OBJ# phasar-llvm  -m ./src/A_cpp.ll -C DTA  -O out --emit-cg-as-json --entry-points  @_ZN2xxxx
PhASAR v1220
A LLVM-based static analysis framework

LLVM ERROR: Could not retrieve function for entry point

```

**Comment by bingosxs** [comment]
It turns out, EntryPoints: main not found. 
And this file does not contain main. Why main is required?

**Comment by bingosxs** [comment]
The main is defined as an external function

**Comment by MMory** [comment]
Please try without the @ prefix in front of the function name.
