### ISSUE TITLE
LLVMBasedICFG does not seem to recognize Call instructions containing BitCast

### ISSUE THREAD

**Issue by flix-** [secure-software-engineering/phasar#25]
My IR contains several call instruction that contain BitCasts:

_%call27 = call i32 bitcast (i32 (%struct.evp_md_ctx_st.2295*, %struct.evp_md_st.2287*, %struct.engine_st.1947*)* @EVP_DigestInit_ex to i32 (%struct.evp_md_ctx_st.2295*, %struct.evp_md_st*, %struct.engine_st*)*)(%struct.evp_md_ctx_st.22    95* %19, %struct.evp_md_st* %20, %struct.engine_st* %21), !dbg !246857_

Those call instructions do not seem to be detected. When running an IFDS analysis the function was never entered and it also didn't show up in the printed call graph. Temporary removing the BitCast resolved the problem.

**Comment by flix-** [comment]
The IR I was using can be found here: [https://filebin.ca/4XL7JlkYwcrN/libcrypto.so.ll](url)

Use HMAC_Init_ex as entry point. The function EVP_DigestInit_ex is not processed here.

**Comment by MarcelHB** [comment]
I had faced a similar issue in #16 

My solution was to subtype `psr::LLVMBasedICFG` with an own implementation that makes use of a pointer solver that is a subtype of `psr::OTFResolver` that can look through `llvm::BitCastInst` to report them as call targets.

**Comment by pdschubert** [comment]
For the example given by flix, points-to information are not necessary. The following code will do as the function is still called 'by name':
const llvm::Value *V = CS.getCalledValue();
const llvm::Value *SV = V->stripPointerCasts();
if (SV->hasName()) {
    llvm::StringRef Fname = SV->getName();
    if (const llvm::Function *F = Mod->getFunction(Fname)) {
        // use F
    }
}
The LLVM IR can be strange sometimes ... I will commit the fix in a minute such that all call-graph algorithms will be able to correctly resolve flix's type of call-sites.

Cheers
