### ISSUE TITLE
How to write a plugin to generate CFG for phasar

### ISSUE THREAD

**Issue by wuxiaoqiang12** [secure-software-engineering/phasar#299]
I read the slides about phasar from your website. I noticed the plugin feature maybe solve my problem. I don't need that deep about call graph such as some library function etc. So I would like to know how to control the call graph depth or how to write an plugin and how to use it. Any other advice will be helpful. Thank you very much.

**Comment by wuxiaoqiang12** [comment]
I find the file called `phasar/lib/PhasarLLVM/Plugins/ICFGTestPlugin.cxx`. I built the `.so` file, but I don't know how to call it. I saw the  help info about command `phasar-llvm` has option `--callgraph-plugin`, but it doesn't work. This argument doesn't processed in phasar-llvm.cpp file, in which the `analysis-plugin` was processed. So, please help me, thanks.

**Comment by blipper** [comment]
The documentation on this part... is not good.  

phasar-llvm -m <PATH TO LL MODULE FILE> -D Plugin --emit-text-report --analysis-plugin <ABSOLUTE PATH TO .SO>

**Comment by wuxiaoqiang12** [comment]
Oh, it works thank you very much. Thanks the great work from your guys.

**Comment by me22bee** [comment]
> I built the `.so` file

Hi,
Can you please guide me on how did you build it?
Thank you

**Comment by me22bee** [comment]
> I built the `.so` file

Hi,
Can you please guide me on how did you build it?
Thank you
