### ISSUE TITLE
dlopen, dlclose: Initialization and finalization functions

### ISSUE THREAD

**Issue by pdschubert** [secure-software-engineering/phasar#3]
When implementing plug-ins on Linux one can annotate a function to be an initialization function that is executed on load and a finalization function that is executed on unload using `__attribute__((constructor))` and `__attribute__((destructor))`.

What is the equivalent on OSX?

**Comment by AlexDenisov** [comment]
It's the same on macOS. Does it not work on mac for you?

**Comment by pdschubert** [comment]
Thanks, good to know that the error is not caused by the annotation.
I have been able to set-up a test environment. Trying to compile the example plugin-in in examples/plugins using the Makefile I obtain the following error message:
```
Undefined symbols for architecture x86_64:
  "psr::LLVMZeroValue::getInstance()", referenced from:
      psr::IFDSTabulationProblemPlugin::createZeroValue() in MyIFDSProblem-b6d318.o
  "psr::llvmIRToString(llvm::Value const*)", referenced from:
      psr::IFDSTabulationProblemPlugin::DtoString(llvm::Value const*) const in MyIFDSProblem-b6d318
.o
      psr::IFDSTabulationProblemPlugin::NtoString(llvm::Instruction const*) const in MyIFDSProblem-
b6d318.o
      psr::IFDSTabulationProblemPlugin::MtoString(llvm::Function const*) const in MyIFDSProblem-b6d
318.o
  "psr::isLLVMZeroValue(llvm::Value const*)", referenced from:
      psr::IFDSTabulationProblemPlugin::isZeroValue(llvm::Value const*) const in MyIFDSProblem-b6d3
18.o
  "psr::IFDSTabulationProblemPluginFactory", referenced from:
      init() in MyIFDSProblem-b6d318.o
  "llvm::DisableABIBreakingChecks", referenced from:
      llvm::VerifyDisableABIBreakingChecks in MyIFDSProblem-b6d318.o
  "boost::system::generic_category()", referenced from:
      boost::system::error_category::std_category::equivalent(int, std::__1::error_condition const&) const in MyIFDSProblem-b6d318.o
      boost::system::error_category::std_category::equivalent(std::__1::error_code const&, int) const in MyIFDSProblem-b6d318.o
ld: symbol(s) not found for architecture x86_64
clang-5.0: error: linker command failed with exit code 1 (use -v to see invocation)
```
As I am an Ubuntu user, my clang++ compiler links against gcc's version of the C++ standard library - in this scenario everything works perfectly fine. Whereas on OSX libc++ is used and it breaks. Also, I have been told that this could be caused by ABI incompatibilities. Do you have a clue?

**Comment by AlexDenisov** [comment]
Hi @pdschubert, I am a Mac user, so maybe I could help with debugging.
Could you please provide exact sequence of steps you did?
I looked at the `Makefile` for the plugin, but I can see neither linker flags (`-L/-l`) nor I can see compiler flags (`-I`) for phasar.
Am I missing something?
