### ISSUE TITLE
Releases do not contain external repos and thus fail to compile

### ISSUE THREAD

**Issue by Inventitech** [secure-software-engineering/phasar#30]
(I pulled the latest release from Releases.)

**Comment by Inventitech** [comment]
FWIW, error message is

```
CMake Error at CMakeLists.txt:82 (add_subdirectory):
  The source directory

    /root/phasar-0319/external/json

  does not contain a CMakeLists.txt file.
```

**Comment by pdschubert** [comment]
Phasar uses submodules for some of the external dependencies. Please initialize those submodules first, and then compile the project.
```
$ git submodule init
$ git submodule update
```

**Comment by Inventitech** [comment]
Well, this works if you clone the repository (obviously), but not in the releases, as mentioned above:

```
git submodule init
fatal: not a git repository (or any of the parent directories): .git
```

Steps to reproduce:
`wget https://github.com/secure-software-engineering/phasar/archive/v0319.zip && unzip phasar-0319.zip`

**Comment by bhermann** [comment]
This is indeed a bit impractical... We will discuss. Thanks for reporting!

**Comment by pdschubert** [comment]
To the best of my knowledge it is currently not possible to add submodule files to a Github release.

https://stackoverflow.com/questions/34719785/how-to-add-submodule-files-to-a-github-release
https://github.community/t5/How-to-use-Git-and-GitHub/Create-Release-that-contains-submodule/td-p/12073

If anyone knows a neat way of how to do it, please let me know.

**Comment by Inventitech** [comment]
Hm, you could include a small bash script that checks for whether the folders are submodules and if so, does nothing (clone case).
If they are not (output from git is `fatal: not a git repository`, see above), initialize the submodules via the script.

This script could live besides `./install-llvm-5.0.1.sh`.

**Comment by pdschubert** [comment]
Sounds reasonable. We will implement a small bash script that does the job ;-)

**Comment by pdschubert** [comment]
A small script and a corresponding note (README) has been added in the development branch. It will be merged to master at the end of the month.
