### ISSUE TITLE
Integrate CI into Github Workflow

### ISSUE THREAD

**Issue by blipper** [secure-software-engineering/phasar#306]
**Is your feature request related to a problem? Please describe.**
Since not everyone uses the same build system it would be helpful to have a CI build integrated into the Github workflow so that we can verify we don't break the build.

**Describe the solution you'd like**
https://lab.github.com/githubtraining/github-actions:-continuous-integration

**Describe alternatives you've considered**
??

**Additional context**

**Comment by pdschubert** [comment]
Done, thanks to @vulder.
