### ISSUE TITLE
Document what version of C++ standard Phasar requires

### ISSUE THREAD

**Issue by blipper** [secure-software-engineering/phasar#308]
**Is your feature request related to a problem? Please describe.**
It is unclear what features we can use since the minimum C++ standard version is not specified.  

**Describe the solution you'd like**
Add to the homepage clearly stating this.   Ideally C++ 17 or C++ 20 would be great.

**Describe alternatives you've considered**

**Additional context**

**Comment by MMory** [comment]
Currently we use C++17, as set in the top-level CMakeLists.txt. I agree we should be more explicit about this in form of documentation.

**Comment by pdschubert** [comment]
I made it more explicit now in the `README.md` on the `development` branch and in the wiki. Thanks for the comment.

**Comment by blipper** [comment]
Thanks!
