### ISSUE TITLE
Reformat existing code and enforce formatting for commits

### ISSUE THREAD

**Issue by blipper** [secure-software-engineering/phasar#314]
**Is your feature request related to a problem? Please describe.**
Makes it hard to read the code.

**Describe the solution you'd like**
Enforce with code formatters and commits/merges

**Describe alternatives you've considered**

**Additional context**

**Comment by pdschubert** [comment]
We have started reformatting the existing code and added a whole bunch of automated checks using Github's actions. Thanks, @vulder! 

You may also wish to install a pre-commit hook locally (cf. https://github.com/secure-software-engineering/phasar#installing-phasars-git-pre-commit-hook).
