### ISSUE TITLE
getMetaDataID returns "-1" for unknown/unhandled

### ISSUE THREAD

**Issue by blipper** [secure-software-engineering/phasar#325]
### Bug description
getMetaDataID() returns "-1".  This is not in compliance with the https://llvm.org/docs/LangRef.html#identifiers which requires numeric ids to be unsigned.
This mostly matters for 
@zero_value = constant i2 0, align 4 | ID: -1

stol will fail since it expects unsigned

**Expected result:** 
Either "" or max unsigned int

**Comment by MMory** [comment]
I have doubts whether this is actually a bug.

On the other hand we could run the value annotation pass at a different stage once all llvm::Values are created. If that is even possible.

**Comment by fabianbs96** [comment]
I agree with @MMory. As far as I understand the linked LLVM reference manual, the giodeline applies for the naming of SSA values like %0 or @42. The phasar IDs on the other hand are just metadata that help with writing unittests. So I don't see that actions are required.
