### ISSUE TITLE
Convert llvm::Instruction getAsInstruction calls to use unique_ptr

### ISSUE THREAD

**Issue by blipper** [secure-software-engineering/phasar#326]
**Is your feature request related to a problem? Please describe.**
A common pattern is something like 
          auto *AsI = SVOCE->getAsInstruction();
       <do some stuff>
          AsI->deleteValue();

It is very easy to forget and/or place deleteValue in the correct area

**Describe the solution you'd like**
Convert all calls to use 
https://en.cppreference.com/w/cpp/memory/unique_ptr with custom deleter that automatically calls deleteValue()

**Describe alternatives you've considered**
Maybe create a wrapper function

**Comment by pdschubert** [comment]
That's a good point actually. I'll ask Meret to wrap the return values of `*::getAsInstruction()` into `std::unique_ptr`s.

**Comment by pdschubert** [comment]
Done; except for one place in a field-sensitive taint analysis which is non-trivial to fix. However, that analysis will be replaced by a much more precise and flexible taint analysis relatively soon.
