### ISSUE TITLE
Simplify design and architecture and remove plugin approach

### ISSUE THREAD

**Issue by blipper** [secure-software-engineering/phasar#335]
**Is your feature request related to a problem? Please describe.**
Dynamic plugins are somewhat confusing and more complex that just writing your own static analysis.  Given that Phasar is opensource and doesn't have to deal with binary closure issues.  It seems the only really need is for the command line tool to have a way to extend?

Users could just build a macro version or extend their own version of the command line tool without the need for any dynamic supports and the resulting two (and confusing different ways) .

**Describe the solution you'd like**
Just an idea.

**Comment by pdschubert** [comment]
Thanks for bringing that up, I agree. If only we had the resources.

But some student assistants of mine and I started to get rid of some relics of the past and to improve the overall code base. I hope that the improvements will be visible in a few weeks.

**Comment by blipper** [comment]
Deleting the plugin would not be huge amount of work I don't think.  I can probably try if you are okay with the approach.

**Comment by MMory** [comment]
Plugins were removed some weeks ago. Closing as fixed.
