### ISSUE TITLE
Automatically format code via Clang Tidy GitHub action

### ISSUE THREAD

**Issue by blipper** [secure-software-engineering/phasar#336]
**Is your feature request related to a problem? Please describe.**
Code format is inconsistent and not enforced

**Describe the solution you'd like**
Add action https://github.com/marketplace/actions/clang-format-code-formatter

**Describe alternatives you've considered**
Suicide

**Additional context**

**Comment by MMory** [comment]
haha, no suicide please!

**Comment by MMory** [comment]
Done some time ago.
