### ISSUE TITLE
Document branch model used for SDLC

### ISSUE THREAD

**Issue by blipper** [secure-software-engineering/phasar#337]
**Is your feature request related to a problem? Please describe.**
I raised a bunch of prs against master.  Apparently dev is the appropriate place for this.

**Describe the solution you'd like**
Document this

**Describe alternatives you've considered**

**Additional context**

**Comment by MMory** [comment]
We could delegate this to one of our students I guess.

**Comment by fabianbs96** [comment]
See https://github.com/secure-software-engineering/phasar/wiki/Coding-Conventions#branches
