### ISSUE TITLE
Document when to use forward declarations versus #includes

### ISSUE THREAD

**Issue by blipper** [secure-software-engineering/phasar#338]
**Is your feature request related to a problem? Please describe.**
Not clear to me what the rules are?

**Describe the solution you'd like**
Convert all forward declarations to include style

**Describe alternatives you've considered**
Clarify the policy and criteria

**Additional context**

**Comment by MMory** [comment]
We need to document the policy for this. The implicit policy is: only include when needed, don't if forward declarations suffice.

**Comment by fabianbs96** [comment]
See https://github.com/secure-software-engineering/phasar/wiki/Coding-Conventions#include-vs-forward-declaration
