### ISSUE TITLE
Clarify meaning of https://github.com/secure-software-engineering/phasar/wiki/Writing-an-Inter-Procedural-Monotone-Framework-Analysis-(Using-Call-Strings)

### ISSUE THREAD

**Issue by blipper** [secure-software-engineering/phasar#405]
There is a comment her that "An example for an analysis that is not distributive is full-constant propagation. In simple words a flow function is not distributive if a data-flow fact's validity depends on two or more other data-flow facts (at the same time)"

Can you please expand upon this restriction?  I am interested in writing an IFDS that is similar to the https://checkerframework.org/manual/#constant-value-checker.  Basicaly I want to have a analysis that aggregates a set of values for each variable if they are determinable during the analysis and kills the fact if not (e.g.  Read in from filesystem or network or set to random value).  The above statement makes me think that I need to use Monotone?

**Comment by MMory** [comment]
This depends on how you want to implement your analysis. In very simplified terms, only _linear_ constant propagation is distributive. Which means, you can only propagate constants with expressions CC = a * C + b, with C and CC being variables for which we know a constant values and a and b trivially constant factors. Expressions such as CCC = CC + C will lead to CCC being overapproximated.
