### ISSUE TITLE
unreachable code

### ISSUE THREAD

**Issue by maddin200** [secure-software-engineering/phasar#410]
/lib/PhasarLLVM/DataFlowSolver/IfdsIde/Problems/IFDSUninitializedVariables.cpp line 234
code:
  return make_shared<UVFF>(Curr, UndefValueUses);

  // otherwise we do not care and nothing changes
  return Identity<IFDSUninitializedVariables::d_t>::getInstance(); // <-- unreachable

**Comment by MMory** [comment]
Thanks for pointing that out!
