### ISSUE TITLE
Add save/load methods for LLVMPointsToSet

### ISSUE THREAD

**Issue by ga0** [secure-software-engineering/phasar#411]
**Is your feature request related to a problem? Please describe.**
LLVMPointsToSet takes too much time.

**Describe the solution you'd like**
Since parallelize LLVMPointsToSet is too hard  ( #305 ), providing methods to serialize/deserialize or save/load LLVMPointsToSet may be very useful.

```c++
    ProjectIRDB IRDB({path});
    LLVMPointsToSet PTS(IRDB, false, PointerAnalysisType::CFLAnders);
    std::ofstream PointsToSetCacheFile("/tmp/points_to_set");
    PTS.save(PointsToSetCacheFile);
```

Next time when we want to analyze the same project.

```c++
    ProjectIRDB IRDB({path});
    LLVMPointsToSet PTS(IRDB);
    std::ifstream PointsToSetCacheFile("/tmp/points_to_set");
    PTS.load(PointsToSetCacheFile);
```

This will save much time.

The PointsToSetMap is an unordered_map of llvm::Value* pointers. 
I don't known how to serializing these pointers' relations.
Can you give me some instructions?

**Comment by fabianbs96** [comment]
Updates are in #441
