### ISSUE TITLE
Build Error on Ubuntu 21.10 - removed linux/cyclades.h

### ISSUE THREAD

**Issue by janniclas** [secure-software-engineering/phasar#479]
- [x] I have searched open and closed issues for duplicates
  - [x] I made sure that I am not using an old project version (DO: pull Phasar, update git submodules, rebuild the project and check if the bug is still there)

----------------------------------------

### Bug description
Using Ubuntu 21.10 the build process on the development branch using `./bootstrap.sh` fails. 

### Steps to reproduce
  - run `./bootstraph.sh` on the development branch using ubuntu 21.10

**Actual result:** 
The error `fatal error: linux/cyclades.h: No such file or directory 146 | #include <linux/cyclades.h>` is emitted and the build process fails.

**Expected result:** 
A successfull build. 

**Operating System:**
  - [x] Linux

**Build Type:** 
  - [x] cmake (./bootstrap.sh)

### Possible solution

Doing a quick google search lead me to the assumption that the cyclades.h file was removed during the latest ubuntu update and the necessarry changes are only contained in LLVM 13 not in 12.
I therefore locally merged @MMory pull request https://github.com/secure-software-engineering/phasar/pull/436 into the dev branch and rerun the build process. 
Using LLVM 13 the build process succeeded.

**Comment by MMory** [comment]
what happens when you change the version in bootstrap.sh to 12.0.1? Same thing?

**Comment by janniclas** [comment]
good call, 12.0.1 also works. I guess that update would be a bit less invasive then from 12 to 13 :)

**Comment by janniclas** [comment]
How do we intend to proceed with this? 
Do you want me to  create a pull request to bump the LLVM Version to 12.0.1? 
They state that 12.0.1 should be completly compatible to 12.0.0, but I'm currently not capable of judging if there could be any hidden changes, which would influence this project.

**Comment by MMory** [comment]
With the transition to LLVM 13 this is now resolved.
