### ISSUE TITLE
Linking error - missing LD_LIBRARY_PATH in install script?

### ISSUE THREAD

**Issue by janniclas** [secure-software-engineering/phasar#484]
After installing phasar on Ubunut 21.10 I get the following runtime error.
![image](https://user-images.githubusercontent.com/8062521/149739368-c0fa2ff3-8b65-446d-9b5e-6242a7b83176.png)

I was able to solve this by adding the nested folder `/usr/local/phasar/lib/phasar` to the LD_LIBRARY_PATH as shown here
![image](https://user-images.githubusercontent.com/8062521/149739635-faf6d0e7-b619-419c-9f43-7b7c8ee8a5f0.png)

Is this a problem unique to my setup or should this path be added in the `setEnvironmentVariables.sh`? If it's just missing I can add it in a pull request, I just want to make sure it's not just my problem.

 A quick google search indicates that the folders specified in LD_LIBRARY_PATH are not searched recursivly, which indicates to me that we have to explicitly add it. 

I used the `bootstraph.sh` script to build PHASAR.

**Comment by dristiron03** [comment]
I was also getting the same issue as yours on Ubuntu 18.04.
