### ISSUE TITLE
Help : Dumping Exploded Super Graph

### ISSUE THREAD

**Issue by animeshbchowdhury** [secure-software-engineering/phasar#49]
Hi,

I wanted some help which is not clear to me from Documentation. I wanted to dump the exploded super graph as DOT format or as pdf format. However, in CLI mode, I am only getting the option of printing the same on stdout. Is there any way by which I can dump and export the super-graph ?

I tried to dump the myJsonGraph.json file, present in IDESolver.h file. However, I am unable to interpret the nodes and edges  from there. Please help.

**Comment by pdschubert** [comment]
Hi,

visualizing the ESG is currently a stalled feature. A student of mine wrote some code to display the ESG in an inter-active manner in the web browser. However, the feature requires a bit more work to get it running in Phasar's current version. If you just wish to dump the ESG to a dot file, you can make use of the IDESolver's computedIntra/InterPathEdges variables that are used to record the ESG. You can add some dumpESGToDot() functionality to the IDESolver which uses the problem's printer functions to stringify the variables of interest.

We are happy to help, if you have any further questions.
