### ISSUE TITLE
Using of "deprecated" c++-17 class(MacOs)

### ISSUE THREAD

**Issue by haotianmichael** [secure-software-engineering/phasar#494]
- [x] I have searched open and closed issues for duplicates
  - [x] I made sure that I am not using an old project version (DO: pull Phasar, update git submodules, rebuild the project and check if the bug is still there)

----------------------------------------

### Bug description
I try to build phasar.  And `include/phasar/PhasarLLVM/Pointer/PointsToSetOwner.h` and `include/phasar/PhasarLLVM/Pointer/LLVMPointsToSet.h` use `#include <memory_resource>`, but when I used `brew install llvm@13.0.1` to compile, it emitted errors that `file `memory_resource` not found`.  I replaced this name with `experimental/memory_resoruce`, but it still emitted that `unsynchronized_pool_resource not found`. I did some research as follows:

### Steps to reproduce
  - TestFile.cpp with `experimental/memory_resource` included use class&operations in `namespace pmr ` etc. respectively.
  - Try LLVM 10.0.0/12.0.1/13.0.1 respectively.
  - Use `-std=c++17`
  - make sure PATH well

**Actual result:**  **class&operations commented in `memory_resource` still not found.**

**Expected result:** Worked well.

### Context (Environment)

  - **phasar:** \[324302ae]
  - **googletest:** \[e2239ee6]
  - **json:** \[4f8fba140]
  - **WALi-OpenNWA:** \[ 2bb4aca0]

**Operating System:**
  - [ ] Linux
  - [ ] Windows
  - [x] macOS

**Build Type:**
  - [x] cmake
  - [ ] custom build

### Possible solution
I Googled `libc++` supported c++17's implementations on `memory_resource`
 - [<memory_resource> for libc++](https://quuxplusone.github.io/blog/2018/06/05/libcpp-memory-resource/)
And I saw same situation with mine in stackoverflow
 - [fliesystem not found](https://stackoverflow.com/questions/42633477/macos-clang-c17-filesystem-header-not-found)
 
But still not familiar  well with c++ and libc++, So Please tell me what to do, thanks~

### Example files
**/usr/local/opt/llvm/include/c++/v1/experimental/memory_resource**

**Comment by haotianmichael** [comment]
Roollbacking to 83b519e6 and rebuilding, everything works well. It seems that libc++'s implementation doesn't  support `unsynchronized_pool_resource`? Any help would be grateful.

**Comment by janniclas** [comment]
Clang and specifically apple-clang don't support polymorphic memory resources as seen [here](https://en.cppreference.com/w/cpp/compiler_support). 
Depending on your setup you can try to use the gcc compiler to compile phasar. If you use a MacBook with the new M1 processor then this will be troublesome too, since the gcc support on the M1 is not soo good in my experience. At least I also still struggle to get it running. If you have any progress in this area please let me know. 
![image](https://user-images.githubusercontent.com/8062521/162152881-b4369966-577c-43fe-8345-01d20a2cdc04.png)

**Comment by janniclas** [comment]
Also, feel free to check out this [branch](https://github.com/secure-software-engineering/phasar/tree/f-WorkaroundPmrCompatibilityIssue). This fixed the issues for me.

**Comment by MMory** [comment]
@janniclas can we close this issue?
