### ISSUE TITLE
Phasar build failed in Ubuntu-18.04

### ISSUE THREAD

**Issue by Luweicai** [secure-software-engineering/phasar#497]
- [√] I have searched open and closed issues for duplicates
  - [√] I made sure that I am not using an old project version (DO: pull Phasar, update git submodules, rebuild the project and check if the bug is still there)

----------------------------------------

### Bug description
phasar build failed when use the ./bootstrap.sh

### Steps to reproduce
  - sudo git clone https://github.com/secure-software-engineering/phasar.git
  - cd phasar/
  - sudo ./bootstrap.sh
Another try:
  - git clone https://github.com/secure-software-engineering/phasar.git
  - cd phasar/
  - git submodule init
  - git submodule update
  - comment out "git submodule init" and "git submodule init" in ./booststrap.sh
  - ./bootstrap.sh

**Actual result:** The dependency and llvm installation are successful, when build phasar, it fails with several file fatal error: 'memory_resource' file not found #include <memory_resource> and #include < filesystem >. Details shows at the bottom.

**Expected result:** The phasar builds successfully.

### Context (Environment)

  - **phasar:** \[commit-id] 09983ec724b44012edd286fc351902a670070088
  - **googletest:** \[commit-id] e2239ee6043f73722e7aa812a459f54a28552929
  - **json:** \[commit-id]  4f8fba14066156b73f1189a2b8bd568bde5284c5
  - **WALi-OpenNWA:** \[commit-id] 2bb4aca02c5a5d444fd038e8aa3eecd7d1ccbb99

**Operating System:**
  - [√] Linux Ubuntu-18.04
  - [ ] Windows
  - [ ] macOS

./bootstrap.sh

**Build Type:**
  - [√] cmake
  - [ ] custom build

### Possible solution

Seems the missed <filesystem> and <memory_resource> are boost related file.

### Example files

Details of error report:
[7/808] Building CXX object lib/PhasarLLVM/DataFlowSolver/IfdsIde/C...ifdside.dir/Problems/ExtendedTaintAnalysis/XTaintAnalysisBase.cpp.o
FAILED: lib/PhasarLLVM/DataFlowSolver/IfdsIde/CMakeFiles/phasar_ifdside.dir/Problems/ExtendedTaintAnalysis/XTaintAnalysisBase.cpp.o
/usr/local/llvm-13/bin/clang++ -DBOOST_LOG_DYN_LINK -Dphasar_ifdside_EXPORTS -I. -I../include -I../external/json/single_include -I../external/json-schema-validator/src -I../external/googletest/googletest/include -I../external/googletest/googlemock/include -I/usr/local/llvm-13/include -I../external/WALi-OpenNWA/Source/wali/include -MP -fvisibility-inlines-hidden -fstack-protector-strong -ffunction-sections -fdata-sections -pipe -march=native -Wall -Wextra -Wno-unused-variable -Wno-unused-parameter -Wno-return-type-c-linkage  -fPIC -DDYNAMIC_LOG -O3 -DNDEBUG -fPIC   -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -std=c++17 -MD -MT lib/PhasarLLVM/DataFlowSolver/IfdsIde/CMakeFiles/phasar_ifdside.dir/Problems/ExtendedTaintAnalysis/XTaintAnalysisBase.cpp.o -MF lib/PhasarLLVM/DataFlowSolver/IfdsIde/CMakeFiles/phasar_ifdside.dir/Problems/ExtendedTaintAnalysis/XTaintAnalysisBase.cpp.o.d -o lib/PhasarLLVM/DataFlowSolver/IfdsIde/CMakeFiles/phasar_ifdside.dir/Problems/ExtendedTaintAnalysis/XTaintAnalysisBase.cpp.o -c ../lib/PhasarLLVM/DataFlowSolver/IfdsIde/Problems/ExtendedTaintAnalysis/XTaintAnalysisBase.cpp
In file included from ../lib/PhasarLLVM/DataFlowSolver/IfdsIde/Problems/ExtendedTaintAnalysis/XTaintAnalysisBase.cpp:5:
../include/phasar/PhasarLLVM/TaintConfig/TaintConfig.h:13:10: fatal error: 'filesystem' file not found
#include < filesystem >
         ^~~~~~~~~~~~
1 error generated.
[8/808] Building CXX object lib/PhasarLLVM/DataFlowSolver/IfdsIde/C...r_ifdside.dir/Problems/ExtendedTaintAnalysis/JoinEdgeFunction.cpp.o
FAILED: lib/PhasarLLVM/DataFlowSolver/IfdsIde/CMakeFiles/phasar_ifdside.dir/Problems/ExtendedTaintAnalysis/JoinEdgeFunction.cpp.o
/usr/local/llvm-13/bin/clang++ -DBOOST_LOG_DYN_LINK -Dphasar_ifdside_EXPORTS -I. -I../include -I../external/json/single_include -I../external/json-schema-validator/src -I../external/googletest/googletest/include -I../external/googletest/googlemock/include -I/usr/local/llvm-13/include -I../external/WALi-OpenNWA/Source/wali/include -MP -fvisibility-inlines-hidden -fstack-protector-strong -ffunction-sections -fdata-sections -pipe -march=native -Wall -Wextra -Wno-unused-variable -Wno-unused-parameter -Wno-return-type-c-linkage  -fPIC -DDYNAMIC_LOG -O3 -DNDEBUG -fPIC   -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -std=c++17 -MD -MT lib/PhasarLLVM/DataFlowSolver/IfdsIde/CMakeFiles/phasar_ifdside.dir/Problems/ExtendedTaintAnalysis/JoinEdgeFunction.cpp.o -MF lib/PhasarLLVM/DataFlowSolver/IfdsIde/CMakeFiles/phasar_ifdside.dir/Problems/ExtendedTaintAnalysis/JoinEdgeFunction.cpp.o.d -o lib/PhasarLLVM/DataFlowSolver/IfdsIde/CMakeFiles/phasar_ifdside.dir/Problems/ExtendedTaintAnalysis/JoinEdgeFunction.cpp.o -c ../lib/PhasarLLVM/DataFlowSolver/IfdsIde/Problems/ExtendedTaintAnalysis/JoinEdgeFunction.cpp
In file included from ../lib/PhasarLLVM/DataFlowSolver/IfdsIde/Problems/ExtendedTaintAnalysis/JoinEdgeFunction.cpp:16:
In file included from ../include/phasar/PhasarLLVM/DataFlowSolver/IfdsIde/Problems/ExtendedTaintAnalysis/Helpers.h:25:
../include/phasar/PhasarLLVM/TaintConfig/TaintConfig.h:13:10: fatal error: 'filesystem' file not found
#include < filesystem >
         ^~~~~~~~~~~~
1 error generated.
[9/808] Building CXX object lib/PhasarLLVM/DataFlowSolver/IfdsIde/C...ir/Problems/ExtendedTaintAnalysis/KillIfSanitizedEdgeFunction.cpp.o
FAILED: lib/PhasarLLVM/DataFlowSolver/IfdsIde/CMakeFiles/phasar_ifdside.dir/Problems/ExtendedTaintAnalysis/KillIfSanitizedEdgeFunction.cpp.o
/usr/local/llvm-13/bin/clang++ -DBOOST_LOG_DYN_LINK -Dphasar_ifdside_EXPORTS -I. -I../include -I../external/json/single_include -I../external/json-schema-validator/src -I../external/googletest/googletest/include -I../external/googletest/googlemock/include -I/usr/local/llvm-13/include -I../external/WALi-OpenNWA/Source/wali/include -MP -fvisibility-inlines-hidden -fstack-protector-strong -ffunction-sections -fdata-sections -pipe -march=native -Wall -Wextra -Wno-unused-variable -Wno-unused-parameter -Wno-return-type-c-linkage  -fPIC -DDYNAMIC_LOG -O3 -DNDEBUG -fPIC   -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -std=c++17 -MD -MT lib/PhasarLLVM/DataFlowSolver/IfdsIde/CMakeFiles/phasar_ifdside.dir/Problems/ExtendedTaintAnalysis/KillIfSanitizedEdgeFunction.cpp.o -MF lib/PhasarLLVM/DataFlowSolver/IfdsIde/CMakeFiles/phasar_ifdside.dir/Problems/ExtendedTaintAnalysis/KillIfSanitizedEdgeFunction.cpp.o.d -o lib/PhasarLLVM/DataFlowSolver/IfdsIde/CMakeFiles/phasar_ifdside.dir/Problems/ExtendedTaintAnalysis/KillIfSanitizedEdgeFunction.cpp.o -c ../lib/PhasarLLVM/DataFlowSolver/IfdsIde/Problems/ExtendedTaintAnalysis/KillIfSanitizedEdgeFunction.cpp
In file included from ../lib/PhasarLLVM/DataFlowSolver/IfdsIde/Problems/ExtendedTaintAnalysis/KillIfSanitizedEdgeFunction.cpp:15:
In file included from ../include/phasar/PhasarLLVM/DataFlowSolver/IfdsIde/Problems/ExtendedTaintAnalysis/JoinEdgeFunction.h:16:
In file included from ../include/phasar/PhasarLLVM/DataFlowSolver/IfdsIde/Problems/ExtendedTaintAnalysis/Helpers.h:25:
../include/phasar/PhasarLLVM/TaintConfig/TaintConfig.h:13:10: fatal error: 'filesystem' file not found
#include < filesystem >
         ^~~~~~~~~~~~
1 error generated.
[10/808] Building CXX object lib/PhasarLLVM/DataFlowSolver/IfdsIde/...dside.dir/Problems/ExtendedTaintAnalysis/TransferEdgeFunction.cpp.o
FAILED: lib/PhasarLLVM/DataFlowSolver/IfdsIde/CMakeFiles/phasar_ifdside.dir/Problems/ExtendedTaintAnalysis/TransferEdgeFunction.cpp.o
/usr/local/llvm-13/bin/clang++ -DBOOST_LOG_DYN_LINK -Dphasar_ifdside_EXPORTS -I. -I../include -I../external/json/single_include -I../external/json-schema-validator/src -I../external/googletest/googletest/include -I../external/googletest/googlemock/include -I/usr/local/llvm-13/include -I../external/WALi-OpenNWA/Source/wali/include -MP -fvisibility-inlines-hidden -fstack-protector-strong -ffunction-sections -fdata-sections -pipe -march=native -Wall -Wextra -Wno-unused-variable -Wno-unused-parameter -Wno-return-type-c-linkage  -fPIC -DDYNAMIC_LOG -O3 -DNDEBUG -fPIC   -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -std=c++17 -MD -MT lib/PhasarLLVM/DataFlowSolver/IfdsIde/CMakeFiles/phasar_ifdside.dir/Problems/ExtendedTaintAnalysis/TransferEdgeFunction.cpp.o -MF lib/PhasarLLVM/DataFlowSolver/IfdsIde/CMakeFiles/phasar_ifdside.dir/Problems/ExtendedTaintAnalysis/TransferEdgeFunction.cpp.o.d -o lib/PhasarLLVM/DataFlowSolver/IfdsIde/CMakeFiles/phasar_ifdside.dir/Problems/ExtendedTaintAnalysis/TransferEdgeFunction.cpp.o -c ../lib/PhasarLLVM/DataFlowSolver/IfdsIde/Problems/ExtendedTaintAnalysis/TransferEdgeFunction.cpp
In file included from ../lib/PhasarLLVM/DataFlowSolver/IfdsIde/Problems/ExtendedTaintAnalysis/TransferEdgeFunction.cpp:14:
In file included from ../include/phasar/PhasarLLVM/DataFlowSolver/IfdsIde/Problems/ExtendedTaintAnalysis/JoinEdgeFunction.h:16:
In file included from ../include/phasar/PhasarLLVM/DataFlowSolver/IfdsIde/Problems/ExtendedTaintAnalysis/Helpers.h:25:
../include/phasar/PhasarLLVM/TaintConfig/TaintConfig.h:13:10: fatal error: 'filesystem' file not found
#include < filesystem >
         ^~~~~~~~~~~~
1 error generated.
[11/808] Building CXX object lib/PhasarLLVM/DataFlowSolver/IfdsIde/...les/phasar_ifdside.dir/Problems/ExtendedTaintAnalysis/Helpers.cpp.o
FAILED: lib/PhasarLLVM/DataFlowSolver/IfdsIde/CMakeFiles/phasar_ifdside.dir/Problems/ExtendedTaintAnalysis/Helpers.cpp.o
/usr/local/llvm-13/bin/clang++ -DBOOST_LOG_DYN_LINK -Dphasar_ifdside_EXPORTS -I. -I../include -I../external/json/single_include -I../external/json-schema-validator/src -I../external/googletest/googletest/include -I../external/googletest/googlemock/include -I/usr/local/llvm-13/include -I../external/WALi-OpenNWA/Source/wali/include -MP -fvisibility-inlines-hidden -fstack-protector-strong -ffunction-sections -fdata-sections -pipe -march=native -Wall -Wextra -Wno-unused-variable -Wno-unused-parameter -Wno-return-type-c-linkage  -fPIC -DDYNAMIC_LOG -O3 -DNDEBUG -fPIC   -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -std=c++17 -MD -MT lib/PhasarLLVM/DataFlowSolver/IfdsIde/CMakeFiles/phasar_ifdside.dir/Problems/ExtendedTaintAnalysis/Helpers.cpp.o -MF lib/PhasarLLVM/DataFlowSolver/IfdsIde/CMakeFiles/phasar_ifdside.dir/Problems/ExtendedTaintAnalysis/Helpers.cpp.o.d -o lib/PhasarLLVM/DataFlowSolver/IfdsIde/CMakeFiles/phasar_ifdside.dir/Problems/ExtendedTaintAnalysis/Helpers.cpp.o -c ../lib/PhasarLLVM/DataFlowSolver/IfdsIde/Problems/ExtendedTaintAnalysis/Helpers.cpp
In file included from ../lib/PhasarLLVM/DataFlowSolver/IfdsIde/Problems/ExtendedTaintAnalysis/Helpers.cpp:17:
In file included from ../include/phasar/PhasarLLVM/DataFlowSolver/IfdsIde/Problems/ExtendedTaintAnalysis/Helpers.h:25:
../include/phasar/PhasarLLVM/TaintConfig/TaintConfig.h:13:10: fatal error: 'filesystem' file not found
#include < filesystem >
         ^~~~~~~~~~~~
1 error generated.
[12/808] Building CXX object lib/PhasarLLVM/DataFlowSolver/IfdsIde/...ide.dir/Problems/ExtendedTaintAnalysis/XTaintEdgeFunctionBase.cpp.o
FAILED: lib/PhasarLLVM/DataFlowSolver/IfdsIde/CMakeFiles/phasar_ifdside.dir/Problems/ExtendedTaintAnalysis/XTaintEdgeFunctionBase.cpp.o
/usr/local/llvm-13/bin/clang++ -DBOOST_LOG_DYN_LINK -Dphasar_ifdside_EXPORTS -I. -I../include -I../external/json/single_include -I../external/json-schema-validator/src -I../external/googletest/googletest/include -I../external/googletest/googlemock/include -I/usr/local/llvm-13/include -I../external/WALi-OpenNWA/Source/wali/include -MP -fvisibility-inlines-hidden -fstack-protector-strong -ffunction-sections -fdata-sections -pipe -march=native -Wall -Wextra -Wno-unused-variable -Wno-unused-parameter -Wno-return-type-c-linkage  -fPIC -DDYNAMIC_LOG -O3 -DNDEBUG -fPIC   -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -std=c++17 -MD -MT lib/PhasarLLVM/DataFlowSolver/IfdsIde/CMakeFiles/phasar_ifdside.dir/Problems/ExtendedTaintAnalysis/XTaintEdgeFunctionBase.cpp.o -MF lib/PhasarLLVM/DataFlowSolver/IfdsIde/CMakeFiles/phasar_ifdside.dir/Problems/ExtendedTaintAnalysis/XTaintEdgeFunctionBase.cpp.o.d -o lib/PhasarLLVM/DataFlowSolver/IfdsIde/CMakeFiles/phasar_ifdside.dir/Problems/ExtendedTaintAnalysis/XTaintEdgeFunctionBase.cpp.o -c ../lib/PhasarLLVM/DataFlowSolver/IfdsIde/Problems/ExtendedTaintAnalysis/XTaintEdgeFunctionBase.cpp
In file included from ../lib/PhasarLLVM/DataFlowSolver/IfdsIde/Problems/ExtendedTaintAnalysis/XTaintEdgeFunctionBase.cpp:13:
In file included from ../include/phasar/PhasarLLVM/DataFlowSolver/IfdsIde/Problems/ExtendedTaintAnalysis/Helpers.h:25:
../include/phasar/PhasarLLVM/TaintConfig/TaintConfig.h:13:10: fatal error: 'filesystem' file not found
#include < filesystem >
         ^~~~~~~~~~~~
1 error generated.
[13/808] Building CXX object lib/PhasarLLVM/DataFlowSolver/IfdsIde/...ar_ifdside.dir/Problems/ExtendedTaintAnalysis/GenEdgeFunction.cpp.o
FAILED: lib/PhasarLLVM/DataFlowSolver/IfdsIde/CMakeFiles/phasar_ifdside.dir/Problems/ExtendedTaintAnalysis/GenEdgeFunction.cpp.o
/usr/local/llvm-13/bin/clang++ -DBOOST_LOG_DYN_LINK -Dphasar_ifdside_EXPORTS -I. -I../include -I../external/json/single_include -I../external/json-schema-validator/src -I../external/googletest/googletest/include -I../external/googletest/googlemock/include -I/usr/local/llvm-13/include -I../external/WALi-OpenNWA/Source/wali/include -MP -fvisibility-inlines-hidden -fstack-protector-strong -ffunction-sections -fdata-sections -pipe -march=native -Wall -Wextra -Wno-unused-variable -Wno-unused-parameter -Wno-return-type-c-linkage  -fPIC -DDYNAMIC_LOG -O3 -DNDEBUG -fPIC   -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -std=c++17 -MD -MT lib/PhasarLLVM/DataFlowSolver/IfdsIde/CMakeFiles/phasar_ifdside.dir/Problems/ExtendedTaintAnalysis/GenEdgeFunction.cpp.o -MF lib/PhasarLLVM/DataFlowSolver/IfdsIde/CMakeFiles/phasar_ifdside.dir/Problems/ExtendedTaintAnalysis/GenEdgeFunction.cpp.o.d -o lib/PhasarLLVM/DataFlowSolver/IfdsIde/CMakeFiles/phasar_ifdside.dir/Problems/ExtendedTaintAnalysis/GenEdgeFunction.cpp.o -c ../lib/PhasarLLVM/DataFlowSolver/IfdsIde/Problems/ExtendedTaintAnalysis/GenEdgeFunction.cpp
In file included from ../lib/PhasarLLVM/DataFlowSolver/IfdsIde/Problems/ExtendedTaintAnalysis/GenEdgeFunction.cpp:14:
In file included from ../include/phasar/PhasarLLVM/DataFlowSolver/IfdsIde/Problems/ExtendedTaintAnalysis/Helpers.h:25:
../include/phasar/PhasarLLVM/TaintConfig/TaintConfig.h:13:10: fatal error: 'filesystem' file not found
#include < filesystem >
         ^~~~~~~~~~~~
1 error generated.
[14/808] Building CXX object lib/PhasarLLVM/DataFlowSolver/IfdsIde/...side.dir/Problems/ExtendedTaintAnalysis/JoinConstEdgeFunction.cpp.o
FAILED: lib/PhasarLLVM/DataFlowSolver/IfdsIde/CMakeFiles/phasar_ifdside.dir/Problems/ExtendedTaintAnalysis/JoinConstEdgeFunction.cpp.o
/usr/local/llvm-13/bin/clang++ -DBOOST_LOG_DYN_LINK -Dphasar_ifdside_EXPORTS -I. -I../include -I../external/json/single_include -I../external/json-schema-validator/src -I../external/googletest/googletest/include -I../external/googletest/googlemock/include -I/usr/local/llvm-13/include -I../external/WALi-OpenNWA/Source/wali/include -MP -fvisibility-inlines-hidden -fstack-protector-strong -ffunction-sections -fdata-sections -pipe -march=native -Wall -Wextra -Wno-unused-variable -Wno-unused-parameter -Wno-return-type-c-linkage  -fPIC -DDYNAMIC_LOG -O3 -DNDEBUG -fPIC   -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -std=c++17 -MD -MT lib/PhasarLLVM/DataFlowSolver/IfdsIde/CMakeFiles/phasar_ifdside.dir/Problems/ExtendedTaintAnalysis/JoinConstEdgeFunction.cpp.o -MF lib/PhasarLLVM/DataFlowSolver/IfdsIde/CMakeFiles/phasar_ifdside.dir/Problems/ExtendedTaintAnalysis/JoinConstEdgeFunction.cpp.o.d -o lib/PhasarLLVM/DataFlowSolver/IfdsIde/CMakeFiles/phasar_ifdside.dir/Problems/ExtendedTaintAnalysis/JoinConstEdgeFunction.cpp.o -c ../lib/PhasarLLVM/DataFlowSolver/IfdsIde/Problems/ExtendedTaintAnalysis/JoinConstEdgeFunction.cpp
In file included from ../lib/PhasarLLVM/DataFlowSolver/IfdsIde/Problems/ExtendedTaintAnalysis/JoinConstEdgeFunction.cpp:14:
In file included from ../include/phasar/PhasarLLVM/DataFlowSolver/IfdsIde/Problems/ExtendedTaintAnalysis/Helpers.h:25:
../include/phasar/PhasarLLVM/TaintConfig/TaintConfig.h:13:10: fatal error: 'filesystem' file not found
#include < filesystem >
         ^~~~~~~~~~~~
1 error generated.
[15/808] Building CXX object lib/PhasarLLVM/DataFlowSolver/IfdsIde/...fdside.dir/Problems/ExtendedTaintAnalysis/ComposeEdgeFunction.cpp.o
FAILED: lib/PhasarLLVM/DataFlowSolver/IfdsIde/CMakeFiles/phasar_ifdside.dir/Problems/ExtendedTaintAnalysis/ComposeEdgeFunction.cpp.o
/usr/local/llvm-13/bin/clang++ -DBOOST_LOG_DYN_LINK -Dphasar_ifdside_EXPORTS -I. -I../include -I../external/json/single_include -I../external/json-schema-validator/src -I../external/googletest/googletest/include -I../external/googletest/googlemock/include -I/usr/local/llvm-13/include -I../external/WALi-OpenNWA/Source/wali/include -MP -fvisibility-inlines-hidden -fstack-protector-strong -ffunction-sections -fdata-sections -pipe -march=native -Wall -Wextra -Wno-unused-variable -Wno-unused-parameter -Wno-return-type-c-linkage  -fPIC -DDYNAMIC_LOG -O3 -DNDEBUG -fPIC   -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -std=c++17 -MD -MT lib/PhasarLLVM/DataFlowSolver/IfdsIde/CMakeFiles/phasar_ifdside.dir/Problems/ExtendedTaintAnalysis/ComposeEdgeFunction.cpp.o -MF lib/PhasarLLVM/DataFlowSolver/IfdsIde/CMakeFiles/phasar_ifdside.dir/Problems/ExtendedTaintAnalysis/ComposeEdgeFunction.cpp.o.d -o lib/PhasarLLVM/DataFlowSolver/IfdsIde/CMakeFiles/phasar_ifdside.dir/Problems/ExtendedTaintAnalysis/ComposeEdgeFunction.cpp.o -c ../lib/PhasarLLVM/DataFlowSolver/IfdsIde/Problems/ExtendedTaintAnalysis/ComposeEdgeFunction.cpp
In file included from ../lib/PhasarLLVM/DataFlowSolver/IfdsIde/Problems/ExtendedTaintAnalysis/ComposeEdgeFunction.cpp:12:
In file included from ../include/phasar/PhasarLLVM/DataFlowSolver/IfdsIde/Problems/ExtendedTaintAnalysis/Helpers.h:25:
../include/phasar/PhasarLLVM/TaintConfig/TaintConfig.h:13:10: fatal error: 'filesystem' file not found
#include < filesystem >
         ^~~~~~~~~~~~
1 error generated.
[17/808] Building CXX object lib/PhasarLLVM/ControlFlow/CMakeFiles/phasar_controlflow.dir/Resolver/OTFResolver.cpp.o
FAILED: lib/PhasarLLVM/ControlFlow/CMakeFiles/phasar_controlflow.dir/Resolver/OTFResolver.cpp.o
/usr/local/llvm-13/bin/clang++ -DBOOST_LOG_DYN_LINK -Dphasar_controlflow_EXPORTS -I. -I../include -I../external/json/single_include -I../external/json-schema-validator/src -I../external/googletest/googletest/include -I../external/googletest/googlemock/include -I/usr/local/llvm-13/include -I../external/WALi-OpenNWA/Source/wali/include -MP -fvisibility-inlines-hidden -fstack-protector-strong -ffunction-sections -fdata-sections -pipe -march=native -Wall -Wextra -Wno-unused-variable -Wno-unused-parameter -Wno-return-type-c-linkage  -fPIC -DDYNAMIC_LOG -O3 -DNDEBUG -fPIC   -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -std=c++17 -MD -MT lib/PhasarLLVM/ControlFlow/CMakeFiles/phasar_controlflow.dir/Resolver/OTFResolver.cpp.o -MF lib/PhasarLLVM/ControlFlow/CMakeFiles/phasar_controlflow.dir/Resolver/OTFResolver.cpp.o.d -o lib/PhasarLLVM/ControlFlow/CMakeFiles/phasar_controlflow.dir/Resolver/OTFResolver.cpp.o -c ../lib/PhasarLLVM/ControlFlow/Resolver/OTFResolver.cpp
In file included from ../lib/PhasarLLVM/ControlFlow/Resolver/OTFResolver.cpp:36:
In file included from ../include/phasar/PhasarLLVM/Pointer/LLVMPointsToGraph.h:27:
../include/phasar/PhasarLLVM/Pointer/PointsToSetOwner.h:13:10: fatal error: 'memory_resource' file not found
#include < memory_resource >
         ^~~~~~~~~~~~~~~~~
1 error generated.
[21/808] Building CXX object lib/PhasarLLVM/DataFlowSolver/IfdsIde/...akeFiles/phasar_ifdside.dir/Problems/IDEExtendedTaintAnalysis.cpp.o
FAILED: lib/PhasarLLVM/DataFlowSolver/IfdsIde/CMakeFiles/phasar_ifdside.dir/Problems/IDEExtendedTaintAnalysis.cpp.o
/usr/local/llvm-13/bin/clang++ -DBOOST_LOG_DYN_LINK -Dphasar_ifdside_EXPORTS -I. -I../include -I../external/json/single_include -I../external/json-schema-validator/src -I../external/googletest/googletest/include -I../external/googletest/googlemock/include -I/usr/local/llvm-13/include -I../external/WALi-OpenNWA/Source/wali/include -MP -fvisibility-inlines-hidden -fstack-protector-strong -ffunction-sections -fdata-sections -pipe -march=native -Wall -Wextra -Wno-unused-variable -Wno-unused-parameter -Wno-return-type-c-linkage  -fPIC -DDYNAMIC_LOG -O3 -DNDEBUG -fPIC   -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -std=c++17 -MD -MT lib/PhasarLLVM/DataFlowSolver/IfdsIde/CMakeFiles/phasar_ifdside.dir/Problems/IDEExtendedTaintAnalysis.cpp.o -MF lib/PhasarLLVM/DataFlowSolver/IfdsIde/CMakeFiles/phasar_ifdside.dir/Problems/IDEExtendedTaintAnalysis.cpp.o.d -o lib/PhasarLLVM/DataFlowSolver/IfdsIde/CMakeFiles/phasar_ifdside.dir/Problems/IDEExtendedTaintAnalysis.cpp.o -c ../lib/PhasarLLVM/DataFlowSolver/IfdsIde/Problems/IDEExtendedTaintAnalysis.cpp
In file included from ../lib/PhasarLLVM/DataFlowSolver/IfdsIde/Problems/IDEExtendedTaintAnalysis.cpp:22:
In file included from ../include/phasar/PhasarLLVM/DataFlowSolver/IfdsIde/Problems/ExtendedTaintAnalysis/Helpers.h:25:
../include/phasar/PhasarLLVM/TaintConfig/TaintConfig.h:13:10: fatal error: 'filesystem' file not found
#include < filesystem >
         ^~~~~~~~~~~~
1 error generated.
[23/808] Building CXX object lib/PhasarLLVM/ControlFlow/CMakeFiles/phasar_controlflow.dir/LLVMBasedICFG.cpp.o
FAILED: lib/PhasarLLVM/ControlFlow/CMakeFiles/phasar_controlflow.dir/LLVMBasedICFG.cpp.o
/usr/local/llvm-13/bin/clang++ -DBOOST_LOG_DYN_LINK -Dphasar_controlflow_EXPORTS -I. -I../include -I../external/json/single_include -I../external/json-schema-validator/src -I../external/googletest/googletest/include -I../external/googletest/googlemock/include -I/usr/local/llvm-13/include -I../external/WALi-OpenNWA/Source/wali/include -MP -fvisibility-inlines-hidden -fstack-protector-strong -ffunction-sections -fdata-sections -pipe -march=native -Wall -Wextra -Wno-unused-variable -Wno-unused-parameter -Wno-return-type-c-linkage  -fPIC -DDYNAMIC_LOG -O3 -DNDEBUG -fPIC   -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -std=c++17 -MD -MT lib/PhasarLLVM/ControlFlow/CMakeFiles/phasar_controlflow.dir/LLVMBasedICFG.cpp.o -MF lib/PhasarLLVM/ControlFlow/CMakeFiles/phasar_controlflow.dir/LLVMBasedICFG.cpp.o.d -o lib/PhasarLLVM/ControlFlow/CMakeFiles/phasar_controlflow.dir/LLVMBasedICFG.cpp.o -c ../lib/PhasarLLVM/ControlFlow/LLVMBasedICFG.cpp
In file included from ../lib/PhasarLLVM/ControlFlow/LLVMBasedICFG.cpp:50:
In file included from ../include/phasar/PhasarLLVM/Pointer/LLVMPointsToGraph.h:27:
../include/phasar/PhasarLLVM/Pointer/PointsToSetOwner.h:13:10: fatal error: 'memory_resource' file not found
#include < memory_resource >
         ^~~~~~~~~~~~~~~~~
1 error generated.
[24/808] Building CXX object lib/PhasarLLVM/DataFlowSolver/IfdsIde/...ide.dir/Problems/ExtendedTaintAnalysis/AbstractMemoryLocation.cpp.o
ninja: build stopped: subcommand failed.

**Files:**

**Comment by fabianbs96** [comment]
Which version of the standard library do you use? If you are using libstdc++ (which should be the default), you need at least GCC (g++) 9 for these headers
