### ISSUE TITLE
Update interface of getCallToReturnFlowFunction

### ISSUE THREAD

**Issue by ericbodden** [secure-software-engineering/phasar#5]
getCallFlowFunction is currently called once separately for every call target. This is how it should be.

getCallToReturnFlowFunction, however, is called only once per call site, getting a set of call targets instead. I think that's quite inconsistent. Is there a good reason for not doing it as in getCallFlowFunction?

**Comment by pdschubert** [comment]
The reason is that getCallFlowFunction handles inter-procedural flows to the possible callees whereas getCallToRetFlowFunction handles intra-procedural flows alongside a given call-site - while there is (usually) only one possible path to be taken.
