### ISSUE TITLE
how can i get a taint path in ifds-taint/ide-xtaint analysis?

### ISSUE THREAD

**Issue by JJ2nu** [secure-software-engineering/phasar#506]
i was trying to get a taint paths from phasar but im having hard time getting those results.

which options do i have to use to get those path information?

**Comment by fabianbs96** [comment]
Hi @JJ2nu,
there is currently no way of getting path information from PhASAR's analyses. However, we are working on a path sensitive analysis. We will eventually integrate it into open-source PhASAR. As of now, you still can retrieve tainted values for any instruction by invoking the `resultsAt` function on the respective IDESolver object.
Does this answer your question?

**Comment by JJ2nu** [comment]
Then could you give me a detailed explanation of how to use resultsAt function?
