### ISSUE TITLE
Auto-detect build directory to successfully run unit tests

### ISSUE THREAD

**Issue by pdschubert** [secure-software-engineering/phasar#510]
Automatically detect the build directory (for the unit tests) to successfully run the unit in more advanced setups.

**Comment by MMory** [comment]
@fabianbs96 @pdschubert this should have been fixed recently, right?

**Comment by fabianbs96** [comment]
If there are problems with that, they will automatically get fixed by #516

**Comment by MMory** [comment]
This should be fixed by a recent PR, am I correct @fabianbs96 ?

**Comment by fabianbs96** [comment]
@MMory, yes that is part of #673

**Comment by MMory** [comment]
fixed with #673
