### ISSUE TITLE
branch and phi instruction

### ISSUE THREAD

**Issue by ihavenomoneybuthope** [secure-software-engineering/phasar#54]
Hi @pdschubert,
thanks for your time.
I got a quick question about how phasar deals with branch.  According to the paper I read that IFDS is distributive over the merge operator.  Is it correct that phasar will execute the 2 paths of the branch and then merge the results at the joining node?

thanks,
best

**Comment by pdschubert** [comment]
Hi,
Yes that is correct: IFDS/IDE follows and analyzes each branch independently and applies the merge operator at the next common successor (joining) node. (In IFDS set union is used as the merge operator. In IDE, the analysis writer can choose how to merge information that is obtained along different branches.)

Cheers,
Philipp
