### ISSUE TITLE
Update CREDITS.txt

### ISSUE THREAD

**Issue by fabianbs96** [secure-software-engineering/phasar#544]
## Story

The CREDITS.txt file is out-dated. Update it

### Prerequisites

* *issue x*

### Out Of Scope

- *A isn't part of this*

### Acceptance Criteria

The following acceptance criteria are defined regarding the result of this story:
*Clarify what the final result should be, not how to accomplish it.*
* [ ] *Criterion 1*
* [ ] *Criterion 2*

### Related Stories

* *none*

### Follow-up Stories

* *none*

**Comment by bleakprestiger** [comment]
Can I take this enhancement ?

**Comment by fabianbs96** [comment]
@bleakprestiger thanks for being willing to contribute to PhASAR. If you are confident tthat you know who are the regular contributors to PhASAR, of course, you can pick this up. Otherwise we might also find another task for you to work on
