### ISSUE TITLE
Using custom entry point function with arguments

### ISSUE THREAD

**Issue by Luweicai** [secure-software-engineering/phasar#549]
Hello, I find that if I give phasar a entry point function which have arguments (except main), it will report a warning. Why can not use a entry point function with arguments? Or is it safe (that not affect the analysis result) to use entry point function with arguments?

**Comment by fabianbs96** [comment]
Hi @Luweicai, the detection of global initializers currently only works properly when the entrypoints are functions without parameters or `main`. So, if you want to use other functions as entry-points I suggest to turn off the detection of global initializers by setting the `IncludeGlobals` parameter of the `LLVMBasedICFG` constructor to `false`.

**Comment by MMory** [comment]
Can we consider this issue as resolved? @Luweicai
