### ISSUE TITLE
How to Uninstall Phasar in Ubuntu 22.

### ISSUE THREAD

**Issue by VenoVeno** [secure-software-engineering/phasar#555]
How to Uninstall Phasar once installed in Ubuntu 22. Uninstall all installed package through the script?

Command used to install:
```
sudo ./bootstrap.sh
```

**Comment by fabianbs96** [comment]
Hi @VenoVeno, it seems that phasar does not provide an uninstall target in cmake. 
We will add it to our todo list. 
To uninstall phasar, you need to remove the installed files. Assuming, your install-prefix is `/usr/local` (which should be the default on your system), you need to delete:
- The whole directory `/usr/local/include/phasar`
- The whole directory `/usr/local/lib/cmake/phasar`
- All files starting with `libphasar` from `/usr/local/lib`
- All files with the substring `phasar` from `/usr/local/bin`
- All files with the substring `phasar` from `/usr/local/bin/DB`
- The whole directory `$HOME/.config/phasar`

Phasar also installs boost, nlohmann_json and nlohmann_json_schema_validator. If you want to uninstall them as well, you can do so in a similar way.
