### ISSUE TITLE
The Tutorial on the webpage doesn't explain how to run phasar

### ISSUE THREAD

**Issue by yurivict** [secure-software-engineering/phasar#567]
The [Tutorial](https://phasar.org/tutorial/) explains what is LLVM's IR, how to install Docker and VBox containers, and how to build phasar, but there is no information on how to run phasar.

**Comment by fabianbs96** [comment]
The webpage phasar.org unfortunately is quite old and needs to be updated (#537). Please refer to our Wiki instead: [Example uses](https://github.com/secure-software-engineering/phasar/wiki/Example-uses), [Getting Started: Running an Analysis](https://github.com/secure-software-engineering/phasar/wiki/Getting-Started:-Running-an-Analysis); this is less out-dated. 

When you have specific questions about running phasar, please just ask here.

**Comment by for-just-we** [comment]
> The webpage phasar.org unfortunately is quite old and needs to be updated (#537). Please refer to our Wiki instead: [Example uses](https://github.com/secure-software-engineering/phasar/wiki/Example-uses), [Getting Started: Running an Analysis](https://github.com/secure-software-engineering/phasar/wiki/Getting-Started:-Running-an-Analysis); this is less out-dated.
> 
> When you have specific questions about running phasar, please just ask here.

So, Phasar runs on IR-level instead of source code-level, right?

**Comment by fabianbs96** [comment]
Yes, PhASAR runs on IR level. If you want to map your results back to source-code you may use the debug info that clang embeds into the IR in debug builds. PhASAR provides some utilities for this in [LLVMIRToSrc.h](https://github.com/secure-software-engineering/phasar/blob/development/include/phasar/PhasarLLVM/Utils/LLVMIRToSrc.h) and some analyses like the ide-lca already make use of it

**Comment by MMory** [comment]
question seems to be answered, closing due to duplicate with #537 and #538
