### ISSUE TITLE
Homebrew formula

### ISSUE THREAD

**Issue by mcandre** [secure-software-engineering/phasar#601]
**Is your feature request related to a problem? Please describe.**

I would love a Homebrew formula for phasar, in order to make it easier to install for newbies on macOS!

**Describe the solution you'd like**

Publish a Homebrew formula for phasar for macOS users.

**Describe alternatives you've considered**

Publish a DMG-archived PKG installer for macOS users.

**Additional context**

A Chocolatey package (Windows), an APT repository (Debian/Ubuntu), \an RPM repository (RHEL), and PKGIN (FreeBSD) would also be welcome.

**Comment by janniclas** [comment]
Hey @mcandre, 
currently, building PhASAR on Macs with the new M Chip Architecture is impossible.  Until this changes, we won't be able to provide a Homebrew formula for Macs.

**Comment by fabianbs96** [comment]
Hi @mcandre, if you want to use phasar on a mac anyway, we have support for Docker. You can find more information at https://github.com/secure-software-engineering/phasar/wiki/OS-Support#macos.

As an outlook to the future, I can tell you that we are working on conan support (#516) that will simplify the whole process of building phasar and managing its dependencies.

Does that answer your question for now?

**Comment by mcandre** [comment]
Yes, I publish a number of Docker images.

While I do love Docker, I do not love having to depend on it for local development.

**Comment by fabianbs96** [comment]
Hi @mcandre, I can totally understand that local development with Docker is not ideal. 
Last time, we tried out phasar on MAC, we needed to use a very recent version of clang for the compilation to succeed. This required us to maintain two versions of LLVM on the system: Clang-17 for compilation and LLVM-14 to link against. As maintaining two LLVM versions can be quite cumbersome, we refrain from recommending this as "official solution". 
However, you can try out, whether it works for you. Unfortunately, I cannot offer you more help, as I am not an Apple user myself

**Comment by mcandre** [comment]
That's fair. Apple doesn't make it easy.

I have done my best to publish tools for streamlining cross platform development. It's an uphill battle.
