### ISSUE TITLE
Bootstrap.sh not working with no boost library installed

### ISSUE THREAD

**Issue by StamesJames** [secure-software-engineering/phasar#611]
- [x] I have searched open and closed issues for duplicates
  - [x] I made sure that I am not using an old project version (DO: pull Phasar, update git submodules, rebuild the project and check if the bug is still there)

----------------------------------------

### Bug description
I tried to install PhASAR with the bootstrap.sh it stopped with no messages at line 87 (I did a little echo debugig to find where it stops). The Line itself works fine (I copied it in a separate script). The Script ran fine after manually installing boost through apt.

### Steps to reproduce
  - use a fresh Ubuntu 22.04 with no boost installed 
  - run bootstrap.sh --install

**Actual result:** Script stopped at line 87

**Expected result:** Script  successfully installs PhASAR and it's dependencies 

### Context (Environment)

  - **phasar:** \[2a941ee81a79883b1e7368aeb34000f3f03b1bed]

**Operating System:**
  - [x] Linux
  - [ ] Windows
  - [ ] macOS

**Build Type:**
  - [x] cmake
  - [ ] custom build

### Possible solution

I think this should be mentioned in the Installation Guide for better ergonomics or the script should work when no boost version is preinstalled.

**Comment by fabianbs96** [comment]
Hi @StamesJames, thanks for your report. I could reproduce your issue. It should be fixed by #612
