### ISSUE TITLE
Is the latest version 0323 or 1222?

### ISSUE THREAD

**Issue by yurivict** [secure-software-engineering/phasar#634]
1222 was tagged earlier, but 0323 is numerically lower.

**Comment by MMory** [comment]
I see the confusion. The version format has been MMYY. If we change it it becomes inconsistent with the past tags. Not sure what the best option is. Assumed default date formats are diverse around the globe. To make it sortable I agree YYMM would be better. Hmm. At least from the releases in Github it should become more clear what is recent.

**Comment by yurivict** [comment]
Automated version discovery systems look at tags and get confused.

**Comment by yurivict** [comment]
To change this for just one port would be unjustified. Also each distro has their own version discovery system.

**Comment by MMory** [comment]
Still the question is how we could convince your version discovery system @yurivict or what else we could do to resolve this issue to your satisfaction. It's not like adding a bunch of tags would be a huge pile of work :)

**Comment by yurivict** [comment]
You can change the versioning system to YYYY.MM.DD, for example.
This system is used by many projects and it also complies to the semantic versioning standard.
There is no need to change old tags, just make a change beginning from new tags.
