### ISSUE TITLE
Ubuntu22 installation error: /usr/bin/ld: cannot find -lstdc++: No such file or directory

### ISSUE THREAD

**Issue by AnonymousAuthor000** [secure-software-engineering/phasar#639]
- [x] I have searched open and closed issues for duplicates
  - [x] I made sure that I am not using an old project version (DO: pull Phasar, update git submodules, rebuild the project and check if the bug is still there)

----------------------------------------

### Bug description
Describe here the issue that you are experiencing.

### Steps to reproduce
  - using hyphens as bullet points
  - list the steps
  - that reproduce the bug
  - e.g. cli arguments and flags

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)

**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)

### Context (Environment)

  - **phasar:** \[commit-id]
  - **googletest:** \[commit-id]
  - **json:** \[commit-id]
  - **WALi-OpenNWA:** \[commit-id]

**Operating System:**
  - [x] Linux
  - [ ] Windows
  - [ ] macOS

Here is the error:

with unit tests.
CMake Warning:
  Ignoring empty string ("") provided on the command line.

-- The CXX compiler identification is Clang 14.0.0
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - failed
-- Check for working CXX compiler: /usr/local/llvm-14/bin/clang++
-- Check for working CXX compiler: /usr/local/llvm-14/bin/clang++ - broken
CMake Error at /home/mingyi/anaconda3/envs/libopt/lib/python3.9/site-packages/cmake/data/share/cmake-3.26/Modules/CMakeTestCXXCompiler.cmake:60 (message):
  The C++ compiler

    "/usr/local/llvm-14/bin/clang++"

  is not able to compile a simple test program.

  It fails with the following output:

    Change Dir: /data/sda/mingyi/DL2C/phasar/build/CMakeFiles/CMakeScratch/TryCompile-zBFeDd
    
    Run Build Command(s):/usr/bin/ninja -v cmTC_e9dcf && [1/2] /usr/local/llvm-14/bin/clang++    -MD -MT CMakeFiles/cmTC_e9dcf.dir/testCXXCompiler.cxx.o -MF CMakeFiles/cmTC_e9dcf.dir/testCXXCompiler.cxx.o.d -o CMakeFiles/cmTC_e9dcf.dir/testCXXCompiler.cxx.o -c /data/sda/mingyi/DL2C/phasar/build/CMakeFiles/CMakeScratch/TryCompile-zBFeDd/testCXXCompiler.cxx
    [2/2] : && /usr/local/llvm-14/bin/clang++   CMakeFiles/cmTC_e9dcf.dir/testCXXCompiler.cxx.o -o cmTC_e9dcf   && :
    FAILED: cmTC_e9dcf 
    : && /usr/local/llvm-14/bin/clang++   CMakeFiles/cmTC_e9dcf.dir/testCXXCompiler.cxx.o -o cmTC_e9dcf   && :
    /usr/bin/ld: cannot find -lstdc++: No such file or directory
    clang-14: error: linker command failed with exit code 1 (use -v to see invocation)
    ninja: build stopped: subcommand failed.

I am using gcc-11. I tried to reinstall the llvm, and it doesn't work.

**Comment by fabianbs96** [comment]
Hi @AnonymousAuthor000, 
the error message indicates that clang cannot link against the C++ standard library. Have you checked whether you can compile a simple program using clang++ or g++? If that does not work I suggest you to try re-installing g++ as clang++ uses the standard libraray implementation from g++. If that does not work, you may want to try out using libc++ instead of libstdc++ which is an alterantive stanrdary library implementation provided by LLVM.

**Comment by rezaarezvan** [comment]
Hey @AnonymousAuthor000 I'm also on Ubuntu 22.04 LTS. [This](https://stackoverflow.com/questions/74543715/usr-bin-ld-cannot-find-lstdc-no-such-file-or-directory-on-running-flutte) worked for me! (Solution 1, top comment)

**Comment by fabianbs96** [comment]
@rezaarezvan, thank you for pointing that out!
@AnonymousAuthor000 does that work for you?

**Comment by AnonymousAuthor000** [comment]
> 

I will try, thanks for your reply.

**Comment by AnonymousAuthor000** [comment]
I installed the libstdc++-12-dev, the problem now is solved. Thanks for all your information.
