### ISSUE TITLE
Which one is better for developing a field sensitive taint analysis

### ISSUE THREAD

**Issue by Luweicai** [secure-software-engineering/phasar#649]
I want to write an taint analysis by myself, However I am a little confused about the current template analysis.
According to the decsription in https://github.com/secure-software-engineering/phasar/wiki/Getting-Started:-Running-an-Analysis  `IDEExtendedTaintAnalysis` is a field-sensitive analysis. however the `IFDSFieldSensTaintAnalysis` seems to be more appropriate according to it's name.

**Comment by MMory** [comment]
Hi @Luweicai , please use `IDEExtendedTaintAnalysis`, the other one will be removed in the foreseeable future.

**Comment by Luweicai** [comment]
Hi @MMory . Thank you very much。
