### ISSUE TITLE
killAllFlows() does not kill fact?

### ISSUE THREAD

**Issue by yuffon** [secure-software-engineering/phasar#681]
Hi, it seems that `killAllFlows()` does not kill facts.

https://github.com/secure-software-engineering/phasar/blob/5ddab3f2ebfb7b289657937928ba45eb95cbf9fe/include/phasar/DataFlow/IfdsIde/FlowFunctions.h#L427

The old deprecated version is OK:
https://github.com/secure-software-engineering/phasar/blob/5ddab3f2ebfb7b289657937928ba45eb95cbf9fe/include/phasar/DataFlow/IfdsIde/FlowFunctions.h#L1123

Is this a bug?

**Comment by fabianbs96** [comment]
This issue has been fixed
