### ISSUE TITLE
function(phasar_config executable) is not executed in phasarConfig.cmake

### ISSUE THREAD

**Issue by yuffon** [secure-software-engineering/phasar#693]
I use phasar as a library.

The definition of ```function(phasar_config executable)``` in `phasarConfig.cmake` is not executed because ```PHASAR_FOUND``` is not set.

**Comment by fabianbs96** [comment]
Hi @yuffon, you are right, we accidentally broke the `phasar_config` function. https://github.com/secure-software-engineering/phasar/tree/f-FixLegacyPhasarConfig should fix this.
However, using `phasar_config` is not the recommended way of using phasar anymore anyway. https://github.com/secure-software-engineering/phasar/blob/f-FixLegacyPhasarConfig/examples/use-phasar-as-library/CMakeLists.txt shows some examples
