### ISSUE TITLE
How to define `LLVMBasedICFG` 

### ISSUE THREAD

**Issue by Mohannadcse** [secure-software-engineering/phasar#696]
- [ x] I have searched open and closed issues for duplicates
  - [ x] I made sure that I am not using an old project version (DO: pull PhASAR, update git submodules, rebuild the project and check if the bug is still there)

----------------------------------------

### Bug description
Seems there is inconsistency in how to define the constructor `LLVMBasedICFG`.  How implementation indicates 3 versions of the constructor. The most widely used one is the following 

```
LLVMBasedICFG(LLVMProjectIRDB *IRDB,
                             CallGraphAnalysisType CGType,
                             llvm::ArrayRef<std::string> EntryPoints,
                             LLVMTypeHierarchy *TH, LLVMAliasInfoRef PT,
                             Soundness S, bool IncludeGlobals)
```

However, this constructor is defined differently in various locations. For example:

- `LLVMBasedICFGGlobCtorDtorTest.cpp`: it's defined as follows. The 5th argument isn't of the type `LLVMAliasInfoRef`, it's actually of the type `LLVMAliasSet`.
```
LLVMProjectIRDB IRDB(PathToLLFiles + "globals_ctor_1_cpp.ll");
LLVMTypeHierarchy TH(IRDB);
LLVMAliasSet PT(&IRDB);

LLVMBasedICFG ICFG(&IRDB, CallGraphAnalysisType::OTF, {"main"}, &TH, &PT,
                     Soundness::Soundy, /*IncludeGlobals*/ true);
```
- `LLVMAliasSetTest.cpp`
```
LLVMAliasSet PTS(&IRDB, false);
LLVMTypeHierarchy TH(IRDB);
LLVMBasedICFG ICF(&IRDB, CallGraphAnalysisType::OTF, {"main"}, &TH, &PTS);
```
Not sure if I'm missing anything,

**Comment by fabianbs96** [comment]
Hi @Mohannadcse,

the `LLVMAliasInfoRef` is a type-erased type that can be constructed from a pointer to any object that provides the required [interface](https://github.com/secure-software-engineering/phasar/blob/development/include/phasar/Pointer/AliasInfoBase.h). `LLVMAliasSet` is the most commonly used type that implements the `AliasInfo` interface, so you can view an `LLVMAliasInfoRef` as sth similar to a pointer-to-base for `LLVMAliasSet`. The type-erased type is defined [here](https://github.com/secure-software-engineering/phasar/blob/development/include/phasar/Pointer/AliasInfo.h).

Does this answer your question?

**Comment by Mohannadcse** [comment]
@fabianbs96 thanks for the clarification.
