### ISSUE TITLE
Accessing pointer analysis

### ISSUE THREAD

**Issue by ericbodden** [secure-software-engineering/phasar#7]
It seems like currently flow functions must access the pointer analysis through the ICFG. I wonder why that is. Why is the pointer analysis an attribute of the ICFG? Should we not instead have some common analysis context that points to both the ICFG and the pointer analysis?

**Comment by pdschubert** [comment]
Can be accessed through the `ProjectIRDB` parameter in the LLVM-based version of the analysis problem interfaces.
