### ISSUE TITLE
 Vulnerability checks based on context-sensitive symbols

### ISSUE THREAD

**Issue by ttllyy111** [secure-software-engineering/phasar#70]
Whether provided SVF pointer analysis framework？ And whethe supports context-sensitive symbolic execution? Thanks!

**Comment by pdschubert** [comment]
No, we do not provide SVF style pointer analysis. As of now, we are using LLVM's flow-insensitive points-to information but are currently working on a highly precise on-demand flow-, field-, and context-sensitive points-to analysis. For more details regarding the precise pointer analysis contact Martin Mory.
