### ISSUE TITLE
PointsToInfo.cpp:64:3: error: implicit instantiation of undefined template 'std::vector<const llvm::Value *>'

### ISSUE THREAD

**Issue by yurivict** [secure-software-engineering/phasar#718]
- [x] I have searched open and closed issues for duplicates
  - [x] I made sure that I am not using an old project version (DO: pull PhASAR, update git submodules, rebuild the project and check if the bug is still there)

----------------------------------------

### Bug description
Build fails because lib/Pointer/PointsToInfo.cpp doesn't have ```#include <vector>```:
```
/wrkdirs/usr/ports/devel/phasar/work/phasar-2403/lib/Pointer/PointsToInfo.cpp:64:3: error: implicit instantiation of undefined template 'std::vector<const llvm::Value *>'
  getInterestingPointersAtImpl(ByConstRef<n_t> /*AtInstruction*/) const {
  ^
/usr/include/c++/v1/iosfwd:260:28: note: template is declared here
class _LIBCPP_TEMPLATE_VIS vector;
                           ^
```

[log](https://pkg-status.freebsd.org/beefy16/data/132amd64-default/0ac48e6731e9/logs/phasar-2403.log)

### Context (Environment)

  - **phasar:** 2403

**Operating System:**
  - [ ] Linux
  - [ ] Windows
  - [ ] macOS
  - [x] FreeBSD

**Build Type:**
  - [ ] cmake
  - [ ] bootstrap.sh
  - [ ] custom build

### Possible solution

We are happy to discuss possible solutions to this problem, especially if it originates from a design flaw.

### Example files

**Files:**

**Comment by fabianbs96** [comment]
Hi @yurivict, thanks for pointing this out. It indeed seems to be an issue, although I could not reproduce it on my system.
Can you check, whether #719 fixes it?

**Comment by yurivict** [comment]
Yes, this patch fixes it.
