### ISSUE TITLE
I cannot see any result

### ISSUE THREAD

**Issue by kjeom** [secure-software-engineering/phasar#74]
I tried to execute phasar built-in analysis(Inter_Mono_TaintAnalysis) with example target(pass_multi_parameter.c.ll)

but I cannot see any results.

I have been done such a something with your virtualbox.ova

There were same problems

Is there any option to show results??

**Comment by pdschubert** [comment]
Which version of Phasar have you been using?
The master branch is currently quite old and will get a massive update sometime this week.
For now I would suggest to use the development branch. As the documentation might be not up-to-date regarding certain aspects you might wish to have a look at the code as well.

**Comment by kjeom** [comment]
I used v0619 and result appeared like below
![phasar_report](https://user-images.githubusercontent.com/18018028/73320287-a3d93180-41f3-11ea-94c4-0558b6142d9c.png)

**Comment by MMory** [comment]
Hi @kjeom do you still have the issue? Otherwise, we are going to close this issue.

**Comment by kjeom** [comment]
hi martin,

thank you for notifying me

you may close the issue.

thank you

2020년 4월 30일 (목) 오후 6:50, Martin Mory <notifications@github.com>님이 작성:
