### ISSUE TITLE
Distributed Work-list Algorithm

### ISSUE THREAD

**Issue by pdschubert** [secure-software-engineering/phasar#76]
Determine if parts of the monotone framework's work-list algorithm can be parallelized to boost overall efficiency of the usually not very scalable approach.

The paper "Toward Full Elasticity in Distributed Static Analysis: The Case of Callgraph Analysis" (ESEC/FSE'17) might be a good starting point.

**Comment by ivan23kor** [comment]
Hi! What is the progress on the issue?
Did I get it right that the issue is parallelizing the functions `solve` in the two files [here](https://github.com/secure-software-engineering/phasar/tree/ed566f284109204afbb96bc140ae64ed532573eb/include/phasar/PhasarLLVM/DataFlowSolver/Mono/Solver)?
