### ISSUE TITLE
Improve on LLVM IR Generation for Unit Tests

### ISSUE THREAD

**Issue by pdschubert** [secure-software-engineering/phasar#78]
Improve the generation of LLVM IR, i.e. the test subjects, for the unit tests. The IR is currently generated by a CMake function. However, this prevents the usage of the distcc compiler wrapper which does not know about Clang specific flags such as `-emit-llvm`. Can the mechanism be somehow adjusted such distcc works fine and we still have a decent mechanism to generate target IR, or can distcc be adjusted to daisy-chain unknown flags as is.

**Comment by MMory** [comment]
I would also like the amount of output to be reduced. Currently two lines are printed per compiled ll file, which is very noisy. it is totally sufficient to have such an output:

[LL] FancyTestCode.c
